### PR TITLE
feat(plasma-web/b2c/hope): Move to plasma-hope b2c components

### PR DESCRIPTION
**Pull request by Yakutoc**
Необходимо: 

1. Перенести компоненты из **plasma-b2c** в **plasma-hope** и сделать **re-export** в 

-  **plasma-b2c**
-  **plasma-web**

Список компонентов: 

    1. AudioPlayer
    2. Editable
    3. ElasticGrid
    4. PreviewGallery
    5. Upload
    6. UploadAudio
    7. UploadVisual

2. Проверить дизайн в **plasma-web**;
3. Если есть ошибки, решать их в отдельных задачах;      

:baby_chick: Download canary assets:

[colors--canary.365.4234690579.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.365.4234690579.xml)  
[color_metro_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.365.4234690579.swift)  
[color_metro_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.365.4234690579.kt)  
[color_metro_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.365.4234690579.ts)  
[color_sberHealth_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.365.4234690579.swift)  
[color_sberHealth_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.365.4234690579.kt)  
[color_sberHealth_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.365.4234690579.ts)  
[color_sbermarket_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.365.4234690579.swift)  
[color_sbermarket_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.365.4234690579.kt)  
[color_sbermarket_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.365.4234690579.ts)  
[color_sberprime_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.365.4234690579.swift)  
[color_sberprime_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.365.4234690579.kt)  
[color_sberprime_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.365.4234690579.ts)  
[color_selgros_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.365.4234690579.swift)  
[color_selgros_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.365.4234690579.kt)  
[color_selgros_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.365.4234690579.ts)  
[color_smbusiness_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.365.4234690579.swift)  
[color_smbusiness_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.365.4234690579.kt)  
[color_smbusiness_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.365.4234690579.ts)  
[PlasmaTokensColor--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.365.4234690579.swift)  
[shadow_sbermarket_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.365.4234690579.ts)  
[typo_mage_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.365.4234690579.swift)  
[typo_mage_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.365.4234690579.kt)  
[typo_mage_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.365.4234690579.ts)  
[typo_plasma_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.365.4234690579.swift)  
[typo_plasma_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.365.4234690579.kt)  
[typo_plasma_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.365.4234690579.ts)  
[typo_ruler_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.365.4234690579.swift)  
[typo_ruler_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.365.4234690579.kt)  
[typo_ruler_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.365.4234690579.ts)  
[typo_sage_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.365.4234690579.swift)  
[typo_sage_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.365.4234690579.kt)  
[typo_sage_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.365.4234690579.ts)  
[typo_sbermarket_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.365.4234690579.swift)  
[typo_sbermarket_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.365.4234690579.kt)  
[typo_sbermarket_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.365.4234690579.ts)  
[typo_soulmate_ios-swift--canary.365.4234690579.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.365.4234690579.swift)  
[typo_soulmate_kotlin--canary.365.4234690579.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.365.4234690579.kt)  
[typo_soulmate_react-native--canary.365.4234690579.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.365.4234690579.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.145.0-canary.365.4234690579.0
  npm install @salutejs/plasma-core@1.100.0-canary.365.4234690579.0
  npm install @salutejs/plasma-hope@0.5.0-canary.365.4234690579.0
  npm install @salutejs/plasma-icons@1.128.0-canary.365.4234690579.0
  npm install @salutejs/plasma-temple@1.139.0-canary.365.4234690579.0
  npm install @salutejs/plasma-ui@1.172.0-canary.365.4234690579.0
  npm install @salutejs/plasma-web@1.171.0-canary.365.4234690579.0
  npm install @salutejs/plasma-cy-utils@0.46.0-canary.365.4234690579.0
  npm install @salutejs/plasma-sb-utils@0.98.0-canary.365.4234690579.0
  # or 
  yarn add @salutejs/plasma-b2c@1.145.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-core@1.100.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-hope@0.5.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-icons@1.128.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-temple@1.139.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-ui@1.172.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-web@1.171.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-cy-utils@0.46.0-canary.365.4234690579.0
  yarn add @salutejs/plasma-sb-utils@0.98.0-canary.365.4234690579.0
  ```
</details>

### CODE REVIEW

**Comment by Yakutoc** [comment]
@Yeti-or @neretin-trike Привет

Как будем реализовать тесты для **plasma-hope**? В том плане какую тему использовать? 

Наши cypress тесты всегда учитывают эту визуальную составляющую.

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-365/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-365/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-365/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-365/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-365/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Yeti-or** [comment]
блин тут 30 коммитов, можешь все же разбить по компонентно ? наверно задачи тоже стоит так разбить?

**Comment by Yakutoc** [comment]
> блин тут 30 коммитов, можешь все же разбить по компонентно ? наверно задачи тоже стоит так разбить?

@Yeti-or Давай сделаем так, разделю на более атомарные PR и к задаче просто линками сделаю. То есть саму задачу не будем дробить.

**Pull request closed without merging**
