### PR TITLE
feat(caldera): add Caldera package

### PR DESCRIPTION
**Pull request by TitanKuzmich**
### Caldera

- добавлена библиотека Caldera
- поднят storybook в рамках pull request
- опубликован npm пакет
- добавлена Typography (в виде компонентов как старого, так и нового формата)
- добавлены компоненты: Button, Checkbox, Dropdown, Link, ModalBase, PopupBase, Radiobox, Segment, Spinner, Switch

### What/why changed

Добавлена новая библиотека компонент Caldera

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/caldera@0.2.0-canary.990.7756942834.0
  npm install @salutejs/sdds-srvc@0.3.0-canary.990.7756942834.0
  # or 
  yarn add @salutejs/caldera@0.2.0-canary.990.7756942834.0
  yarn add @salutejs/sdds-srvc@0.3.0-canary.990.7756942834.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-990/caldera-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-990/caldera-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-990/caldera-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-990/caldera-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-990/caldera-storybook/

**Review by Yakutoc — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-990/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-990/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-990/caldera-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-990/sdds-srvc-storybook/

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera@0.2.0-dev.0, @salutejs/sdds-srvc@0.3.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera@0.2.0-dev.0, @salutejs/sdds-srvc@0.3.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera@0.2.0-dev.0, @salutejs/sdds-srvc@0.3.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.2.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.2.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.2.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.2.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.3.0-dev.0, @salutejs/caldera@0.3.0-dev.0, @salutejs/plasma-asdk@0.38.0-dev.0, @salutejs/plasma-b2c@1.280.0-dev.0, @salutejs/plasma-core@1.148.0-dev.0, @salutejs/plasma-cy-utils@0.80.0-dev.0, @salutejs/plasma-hope@1.261.0-dev.0, @salutejs/plasma-icons@1.181.0-dev.0, @salutejs/plasma-new-hope@0.44.0-dev.0, @salutejs/plasma-sb-utils@0.146.0-dev.0, @salutejs/plasma-temple-docs@0.218.0-dev.0, @salutejs/plasma-temple@1.200.0-dev.0, @salutejs/plasma-tokens-native@1.23.0-dev.0, @salutejs/plasma-tokens@1.72.0-dev.0, @salutejs/plasma-ui-docs@0.267.0-dev.0, @salutejs/plasma-ui@1.232.0-dev.0, @salutejs/plasma-web-docs@0.234.0-dev.0, @salutejs/plasma-web@1.280.0-dev.0, @salutejs/plasma-website@0.242.0-dev.0, @salutejs/sdds-srvc@0.4.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.3.0-dev.0, @salutejs/caldera@0.3.0-dev.0, @salutejs/plasma-asdk@0.38.0-dev.0, @salutejs/plasma-b2c@1.280.0-dev.0, @salutejs/plasma-core@1.148.0-dev.0, @salutejs/plasma-cy-utils@0.80.0-dev.0, @salutejs/plasma-hope@1.261.0-dev.0, @salutejs/plasma-icons@1.181.0-dev.0, @salutejs/plasma-new-hope@0.44.0-dev.0, @salutejs/plasma-sb-utils@0.146.0-dev.0, @salutejs/plasma-temple-docs@0.218.0-dev.0, @salutejs/plasma-temple@1.200.0-dev.0, @salutejs/plasma-tokens-native@1.23.0-dev.0, @salutejs/plasma-tokens@1.72.0-dev.0, @salutejs/plasma-ui-docs@0.267.0-dev.0, @salutejs/plasma-ui@1.232.0-dev.0, @salutejs/plasma-web-docs@0.234.0-dev.0, @salutejs/plasma-web@1.280.0-dev.0, @salutejs/plasma-website@0.242.0-dev.0, @salutejs/sdds-srvc@0.4.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.3.0-dev.0, @salutejs/caldera@0.3.0-dev.0, @salutejs/plasma-asdk@0.38.0-dev.0, @salutejs/plasma-b2c@1.280.0-dev.0, @salutejs/plasma-core@1.148.0-dev.0, @salutejs/plasma-cy-utils@0.80.0-dev.0, @salutejs/plasma-hope@1.261.0-dev.0, @salutejs/plasma-icons@1.181.0-dev.0, @salutejs/plasma-new-hope@0.44.0-dev.0, @salutejs/plasma-sb-utils@0.146.0-dev.0, @salutejs/plasma-temple-docs@0.218.0-dev.0, @salutejs/plasma-temple@1.200.0-dev.0, @salutejs/plasma-tokens-native@1.23.0-dev.0, @salutejs/plasma-tokens@1.72.0-dev.0, @salutejs/plasma-ui-docs@0.267.0-dev.0, @salutejs/plasma-ui@1.232.0-dev.0, @salutejs/plasma-web-docs@0.234.0-dev.0, @salutejs/plasma-web@1.280.0-dev.0, @salutejs/plasma-website@0.242.0-dev.0, @salutejs/sdds-srvc@0.4.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/caldera-online@0.3.0-dev.0, @salutejs/caldera@0.3.0-dev.0, @salutejs/plasma-asdk@0.38.0-dev.0, @salutejs/plasma-b2c@1.280.0-dev.0, @salutejs/plasma-core@1.148.0-dev.0, @salutejs/plasma-cy-utils@0.80.0-dev.0, @salutejs/plasma-hope@1.261.0-dev.0, @salutejs/plasma-icons@1.181.0-dev.0, @salutejs/plasma-new-hope@0.44.0-dev.0, @salutejs/plasma-sb-utils@0.146.0-dev.0, @salutejs/plasma-temple-docs@0.218.0-dev.0, @salutejs/plasma-temple@1.200.0-dev.0, @salutejs/plasma-tokens-native@1.23.0-dev.0, @salutejs/plasma-tokens@1.72.0-dev.0, @salutejs/plasma-ui-docs@0.267.0-dev.0, @salutejs/plasma-ui@1.232.0-dev.0, @salutejs/plasma-web-docs@0.234.0-dev.0, @salutejs/plasma-web@1.280.0-dev.0, @salutejs/plasma-website@0.242.0-dev.0, @salutejs/sdds-srvc@0.4.0-dev.0 🚀

**Pull request merged**
