### PR TITLE
fix(plasma-web): Fix color for header in `Calendar` component

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.192.3283300101.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.192.3283300101.swift)  
[sbermarket_kotlin--canary.192.3283300101.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.192.3283300101.kt)  
[sbermarket_react-native--canary.192.3283300101.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.192.3283300101.ts)  
[sberprime_ios-swift--canary.192.3283300101.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.192.3283300101.swift)  
[sberprime_kotlin--canary.192.3283300101.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_kotlin--canary.192.3283300101.kt)  
[sberprime_react-native--canary.192.3283300101.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_react-native--canary.192.3283300101.ts)  
[colors--canary.192.3283300101.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.192.3283300101.xml)  
[PlasmaTokensColor--canary.192.3283300101.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.192.3283300101.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.103.1-canary.192.3283300101.0
  npm install @salutejs/plasma-web@1.135.1-canary.192.3283300101.0
  # or 
  yarn add @salutejs/plasma-b2c@1.103.1-canary.192.3283300101.0
  yarn add @salutejs/plasma-web@1.135.1-canary.192.3283300101.0
  ```
</details>

### CODE REVIEW

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-192/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-192/
  ui storybook: http://plasma.sberdevices.ru/pr-192/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-192/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-192/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-192/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-192/
  ui storybook: http://plasma.sberdevices.ru/pr-192/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-192/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-192/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-192/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-192/
  ui storybook: http://plasma.sberdevices.ru/pr-192/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-192/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-192/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-192/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-192/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-192/
  ui storybook: http://plasma.sberdevices.ru/pr-192/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-192/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-192/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-192/temple-storybook/

**Pull request merged**
