### PR TITLE
docs(plasma-ui, plasma-web, plasma-temple): add trailing slash

### PR DESCRIPTION
**Pull request by kayman233**
:baby_chick: Download canary assets:

[colors--canary.280.3934298192.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.280.3934298192.xml)  
[color_metro_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.280.3934298192.swift)  
[color_metro_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.280.3934298192.kt)  
[color_metro_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.280.3934298192.ts)  
[color_sbermarket_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.280.3934298192.swift)  
[color_sbermarket_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.280.3934298192.kt)  
[color_sbermarket_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.280.3934298192.ts)  
[color_sberprime_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.280.3934298192.swift)  
[color_sberprime_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.280.3934298192.kt)  
[color_sberprime_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.280.3934298192.ts)  
[color_selgros_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.280.3934298192.swift)  
[color_selgros_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.280.3934298192.kt)  
[color_selgros_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.280.3934298192.ts)  
[color_smbusiness_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.280.3934298192.swift)  
[color_smbusiness_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.280.3934298192.kt)  
[color_smbusiness_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.280.3934298192.ts)  
[PlasmaTokensColor--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.280.3934298192.swift)  
[typo_mage_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.280.3934298192.swift)  
[typo_mage_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.280.3934298192.kt)  
[typo_mage_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.280.3934298192.ts)  
[typo_plasma_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.280.3934298192.swift)  
[typo_plasma_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.280.3934298192.kt)  
[typo_plasma_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.280.3934298192.ts)  
[typo_ruler_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.280.3934298192.swift)  
[typo_ruler_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.280.3934298192.kt)  
[typo_ruler_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.280.3934298192.ts)  
[typo_sage_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.280.3934298192.swift)  
[typo_sage_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.280.3934298192.kt)  
[typo_sage_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.280.3934298192.ts)  
[typo_sbermarket_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.280.3934298192.swift)  
[typo_sbermarket_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.280.3934298192.kt)  
[typo_sbermarket_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.280.3934298192.ts)  
[typo_soulmate_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.280.3934298192.swift)  
[typo_soulmate_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.280.3934298192.kt)  
[typo_soulmate_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.280.3934298192.ts)

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-280/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-280/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-280/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-280/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-280/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-280/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-280/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
