### PR TITLE
fix(plasma-ui): Increase area for touch in `Sheet` component

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[colors--canary.208.3384185184.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.208.3384185184.xml)  
[color_sbermarket_ios-swift--canary.208.3384185184.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.208.3384185184.swift)  
[color_sbermarket_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.208.3384185184.kt)  
[color_sbermarket_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.208.3384185184.ts)  
[color_sberprime_ios-swift--canary.208.3384185184.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.208.3384185184.swift)  
[color_sberprime_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.208.3384185184.kt)  
[color_sberprime_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.208.3384185184.ts)  
[PlasmaTokensColor--canary.208.3384185184.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.208.3384185184.swift)  
[typo_mage_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.208.3384185184.kt)  
[typo_mage_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.208.3384185184.ts)  
[typo_plasma_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.208.3384185184.kt)  
[typo_plasma_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.208.3384185184.ts)  
[typo_ruler_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.208.3384185184.kt)  
[typo_ruler_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.208.3384185184.ts)  
[typo_sage_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.208.3384185184.kt)  
[typo_sage_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.208.3384185184.ts)  
[typo_sbermarket_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.208.3384185184.kt)  
[typo_sbermarket_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.208.3384185184.ts)  
[typo_soulmate_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.208.3384185184.kt)  
[typo_soulmate_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.208.3384185184.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.109.1-canary.208.3384185184.0
  npm install @salutejs/plasma-ui@1.143.1-canary.208.3384185184.0
  # or 
  yarn add @salutejs/plasma-temple@1.109.1-canary.208.3384185184.0
  yarn add @salutejs/plasma-ui@1.143.1-canary.208.3384185184.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-208/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-208/
  ui storybook: http://plasma.sberdevices.ru/pr-208/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-208/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-208/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-208/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-208/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-208/
  ui storybook: http://plasma.sberdevices.ru/pr-208/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-208/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-208/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-208/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-208/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-208/
  ui storybook: http://plasma.sberdevices.ru/pr-208/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-208/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-208/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-208/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-208/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-208/
  ui storybook: http://plasma.sberdevices.ru/pr-208/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-208/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-208/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-208/temple-storybook/

**Comment by Yeti-or** [comment]
Посмотрел всё работает

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-208/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-208/
  ui storybook: http://plasma.sberdevices.ru/pr-208/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-208/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-208/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-208/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-208/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-208/
  ui storybook: http://plasma.sberdevices.ru/pr-208/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-208/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-208/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-208/temple-storybook/

**Pull request merged**
