### PR TITLE
feat(plasma-tokens): generate ios android tokens

### PR DESCRIPTION
**Pull request by kvpolyanskiy**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.88.0-canary.121.2831667832.0
  npm install @salutejs/plasma-core@1.66.0-canary.121.2831667832.0
  npm install @salutejs/plasma-icons@1.92.0-canary.121.2831667832.0
  npm install @salutejs/plasma-temple@1.87.0-canary.121.2831667832.0
  npm install @salutejs/plasma-tokens@1.20.0-canary.121.2831667832.0
  npm install @salutejs/plasma-typo@0.13.0-canary.121.2831667832.0
  npm install @salutejs/plasma-ui@1.121.0-canary.121.2831667832.0
  npm install @salutejs/plasma-web@1.121.0-canary.121.2831667832.0
  npm install @salutejs/plasma-cy-utils@0.19.0-canary.121.2831667832.0
  npm install @salutejs/plasma-sb-utils@0.65.0-canary.121.2831667832.0
  npm install @salutejs/plasma-tokens-android@2.27.0-canary.121.2831667832.0
  npm install @salutejs/plasma-tokens-ios-swift@2.27.0-canary.121.2831667832.0
  # or 
  yarn add @salutejs/plasma-b2c@1.88.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-core@1.66.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-icons@1.92.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-temple@1.87.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-tokens@1.20.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-typo@0.13.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-ui@1.121.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-web@1.121.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-cy-utils@0.19.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-sb-utils@0.65.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-tokens-android@2.27.0-canary.121.2831667832.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.27.0-canary.121.2831667832.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-121/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-121/
  ui storybook: http://plasma.sberdevices.ru/pr-121/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-121/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-121/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-121/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-121/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-121/
  ui storybook: http://plasma.sberdevices.ru/pr-121/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-121/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-121/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-121/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-121/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-121/
  ui storybook: http://plasma.sberdevices.ru/pr-121/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-121/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-121/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-121/temple-storybook/

**Review by Yeti-or — APPROVED** [review]
:shipit:

**Pull request merged**
