### PR TITLE
docs: fix links in docs

### PR DESCRIPTION
**Pull request by kayman233**
Поправлены ссылки в документации на сайте и в github.

:baby_chick: Download canary assets:

[color_sberHealth_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.500.4935994539.swift)  
[color_sberHealth_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.500.4935994539.kt)  
[color_sberHealth_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.500.4935994539.ts)  
[color_sbermarket_business_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.500.4935994539.swift)  
[color_sbermarket_business_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.500.4935994539.kt)  
[color_sbermarket_business_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.500.4935994539.ts)  
[color_sbermarket_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.500.4935994539.swift)  
[color_sbermarket_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.500.4935994539.kt)  
[color_sbermarket_metro_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.500.4935994539.swift)  
[color_sbermarket_metro_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.500.4935994539.kt)  
[color_sbermarket_metro_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.500.4935994539.ts)  
[color_sbermarket_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.500.4935994539.ts)  
[color_sbermarket_selgros_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.500.4935994539.swift)  
[color_sbermarket_selgros_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.500.4935994539.kt)  
[color_sbermarket_selgros_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.500.4935994539.ts)  
[color_sbermarket_wlbusiness_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.500.4935994539.swift)  
[color_sbermarket_wlbusiness_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.500.4935994539.kt)  
[color_sbermarket_wlbusiness_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.500.4935994539.ts)  
[color_sberprime_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.500.4935994539.swift)  
[color_sberprime_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.500.4935994539.kt)  
[color_sberprime_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.500.4935994539.ts)  
[shadow_sbermarket_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.500.4935994539.ts)  
[typo_mage_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.500.4935994539.swift)  
[typo_mage_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.500.4935994539.kt)  
[typo_mage_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.500.4935994539.ts)  
[typo_plasma_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.500.4935994539.swift)  
[typo_plasma_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.500.4935994539.kt)  
[typo_plasma_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.500.4935994539.ts)  
[typo_ruler_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.500.4935994539.swift)  
[typo_ruler_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.500.4935994539.kt)  
[typo_ruler_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.500.4935994539.ts)  
[typo_sage_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.500.4935994539.swift)  
[typo_sage_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.500.4935994539.kt)  
[typo_sage_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.500.4935994539.ts)  
[typo_sbermarket_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.500.4935994539.swift)  
[typo_sbermarket_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.500.4935994539.kt)  
[typo_sbermarket_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.500.4935994539.ts)  
[typo_soulmate_ios-swift--canary.500.4935994539.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.500.4935994539.swift)  
[typo_soulmate_kotlin--canary.500.4935994539.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.500.4935994539.kt)  
[typo_soulmate_react-native--canary.500.4935994539.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.500.4935994539.ts)

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-500/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-500/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-500/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-500/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-500/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-500/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-500/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-500/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-500/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by Yakutoc — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-500/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-500/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-500/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-500/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-500/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-500/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-500/temple-storybook/

**Pull request merged**
