### PR TITLE
feat(plasma-icons): Add icons for `24 dp` from A to E

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.61.0-canary.15.2274770926.0
  npm install @salutejs/plasma-icons@1.79.0-canary.15.2274770926.0
  npm install @salutejs/plasma-temple@1.63.0-canary.15.2274770926.0
  npm install @salutejs/plasma-ui@1.99.0-canary.15.2274770926.0
  npm install @salutejs/plasma-web@1.96.0-canary.15.2274770926.0
  # or 
  yarn add @salutejs/plasma-b2c@1.61.0-canary.15.2274770926.0
  yarn add @salutejs/plasma-icons@1.79.0-canary.15.2274770926.0
  yarn add @salutejs/plasma-temple@1.63.0-canary.15.2274770926.0
  yarn add @salutejs/plasma-ui@1.99.0-canary.15.2274770926.0
  yarn add @salutejs/plasma-web@1.96.0-canary.15.2274770926.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-15/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-15/
  ui storybook: http://plasma.sberdevices.ru/pr-15/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-15/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-15/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-15/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-15/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-15/
  ui storybook: http://plasma.sberdevices.ru/pr-15/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-15/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-15/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-15/temple-storybook/

**Pull request merged**
