### PR TITLE
feat(plasma-tokens): save theme artifacts

### PR DESCRIPTION
**Pull request by kvpolyanskiy**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.91.0-canary.136.2970912092.0
  npm install @salutejs/plasma-core@1.68.0-canary.136.2970912092.0
  npm install @salutejs/plasma-icons@1.94.0-canary.136.2970912092.0
  npm install @salutejs/plasma-temple@1.91.0-canary.136.2970912092.0
  npm install @salutejs/plasma-tokens@1.21.0-canary.136.2970912092.0
  npm install @salutejs/plasma-typo@0.15.0-canary.136.2970912092.0
  npm install @salutejs/plasma-ui@1.125.0-canary.136.2970912092.0
  npm install @salutejs/plasma-web@1.124.0-canary.136.2970912092.0
  npm install @salutejs/plasma-cy-utils@0.21.0-canary.136.2970912092.0
  npm install @salutejs/plasma-sb-utils@0.67.0-canary.136.2970912092.0
  npm install @salutejs/plasma-tokens-android@2.28.0-canary.136.2970912092.0
  npm install @salutejs/plasma-tokens-ios-swift@2.28.0-canary.136.2970912092.0
  # or 
  yarn add @salutejs/plasma-b2c@1.91.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-core@1.68.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-icons@1.94.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-temple@1.91.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-tokens@1.21.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-typo@0.15.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-ui@1.125.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-web@1.124.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-cy-utils@0.21.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-sb-utils@0.67.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-tokens-android@2.28.0-canary.136.2970912092.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.28.0-canary.136.2970912092.0
  ```
</details>

:baby_chick: Download canary assets:

[colors--canary.136.2970912092.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.136.2970912092.xml)  
[PlasmaTokensColor--canary.136.2970912092.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.136.2970912092.swift)

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Yeti-or** [comment]
Вот сюда" https://github.com/salute-developers/plasma/releases/tag/%40salutejs%2Fplasma-website%400.78.0

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-136/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-136/
  ui storybook: http://plasma.sberdevices.ru/pr-136/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-136/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-136/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-136/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
