### PR TITLE
feat: Bump storybook version to 6.5

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[colors--canary.330.4173402721.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.330.4173402721.xml)  
[color_metro_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.330.4173402721.swift)  
[color_metro_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.330.4173402721.kt)  
[color_metro_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.330.4173402721.ts)  
[color_sbermarket_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.330.4173402721.swift)  
[color_sbermarket_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.330.4173402721.kt)  
[color_sbermarket_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.330.4173402721.ts)  
[color_sberprime_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.330.4173402721.swift)  
[color_sberprime_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.330.4173402721.kt)  
[color_sberprime_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.330.4173402721.ts)  
[color_selgros_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.330.4173402721.swift)  
[color_selgros_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.330.4173402721.kt)  
[color_selgros_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.330.4173402721.ts)  
[color_smbusiness_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.330.4173402721.swift)  
[color_smbusiness_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.330.4173402721.kt)  
[color_smbusiness_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.330.4173402721.ts)  
[PlasmaTokensColor--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.330.4173402721.swift)  
[shadow_sbermarket_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.330.4173402721.ts)  
[typo_mage_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.330.4173402721.swift)  
[typo_mage_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.330.4173402721.kt)  
[typo_mage_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.330.4173402721.ts)  
[typo_plasma_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.330.4173402721.swift)  
[typo_plasma_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.330.4173402721.kt)  
[typo_plasma_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.330.4173402721.ts)  
[typo_ruler_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.330.4173402721.swift)  
[typo_ruler_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.330.4173402721.kt)  
[typo_ruler_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.330.4173402721.ts)  
[typo_sage_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.330.4173402721.swift)  
[typo_sage_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.330.4173402721.kt)  
[typo_sage_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.330.4173402721.ts)  
[typo_sbermarket_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.330.4173402721.swift)  
[typo_sbermarket_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.330.4173402721.kt)  
[typo_sbermarket_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.330.4173402721.ts)  
[typo_soulmate_ios-swift--canary.330.4173402721.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.330.4173402721.swift)  
[typo_soulmate_kotlin--canary.330.4173402721.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.330.4173402721.kt)  
[typo_soulmate_react-native--canary.330.4173402721.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.330.4173402721.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.140.0-canary.330.4173402721.0
  npm install @salutejs/plasma-temple@1.134.0-canary.330.4173402721.0
  npm install @salutejs/plasma-ui@1.167.0-canary.330.4173402721.0
  npm install @salutejs/plasma-web@1.166.0-canary.330.4173402721.0
  # or 
  yarn add @salutejs/plasma-b2c@1.140.0-canary.330.4173402721.0
  yarn add @salutejs/plasma-temple@1.134.0-canary.330.4173402721.0
  yarn add @salutejs/plasma-ui@1.167.0-canary.330.4173402721.0
  yarn add @salutejs/plasma-web@1.166.0-canary.330.4173402721.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🌚 Missing base report**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🌚 Missing base report**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🌚 Missing base report**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-330/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-330/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-330/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-330/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-330/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-330/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-330/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-330/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-330/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-330/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-330/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-330/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-330/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-330/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-330/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-330/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-330/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-330/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-330/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-330/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-330/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-330/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-330/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-330/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-330/temple-storybook/

**Comment by Yeti-or** [comment]
@neretin-trike я же правильно понял что мы будем в эту ветку докидывать пр ?

**Comment by neretin-trike** [comment]
> @neretin-trike я же правильно понял что мы будем в эту ветку докидывать пр ?

не, я новую сделал на основе этой: https://github.com/salute-developers/plasma/pull/335

**Review by Yakutoc — APPROVED** [review]

**Comment by Yeti-or** [comment]
то есть это мы не вливаем?

**Comment by neretin-trike** [comment]
> то есть это мы не вливаем?

вливаем, т.к. на отдельные PR и задачи это раздробил

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-330/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-330/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-330/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-330/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-330/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-330/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-330/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
