### PR TITLE
ci: disable renovate

### PR DESCRIPTION
**Pull request by Yeti-or**
https://github.com/renovatebot/renovate/discussions/20455

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-355/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-355/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-355/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-355/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-355/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-355/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-355/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Pull request closed without merging**
