### PR TITLE
feat(plasma-tokens): auto generate ASDK theme

### PR DESCRIPTION
**Pull request by AleksandraIushkova**
:baby_chick: Download canary assets:

[color_asdk_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.518.5269639196.swift)  
[color_asdk_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.518.5269639196.kt)  
[color_asdk_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.518.5269639196.ts)  
[color_sberHealth_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.518.5269639196.swift)  
[color_sberHealth_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.518.5269639196.kt)  
[color_sberHealth_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.518.5269639196.ts)  
[color_sbermarket_business_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.518.5269639196.swift)  
[color_sbermarket_business_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.518.5269639196.kt)  
[color_sbermarket_business_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.518.5269639196.ts)  
[color_sbermarket_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.518.5269639196.swift)  
[color_sbermarket_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.518.5269639196.kt)  
[color_sbermarket_metro_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.518.5269639196.swift)  
[color_sbermarket_metro_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.518.5269639196.kt)  
[color_sbermarket_metro_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.518.5269639196.ts)  
[color_sbermarket_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.518.5269639196.ts)  
[color_sbermarket_selgros_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.518.5269639196.swift)  
[color_sbermarket_selgros_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.518.5269639196.kt)  
[color_sbermarket_selgros_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.518.5269639196.ts)  
[color_sbermarket_wlbusiness_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.518.5269639196.swift)  
[color_sbermarket_wlbusiness_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.518.5269639196.kt)  
[color_sbermarket_wlbusiness_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.518.5269639196.ts)  
[color_sberonline_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_ios-swift--canary.518.5269639196.swift)  
[color_sberonline_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_kotlin--canary.518.5269639196.kt)  
[color_sberonline_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_react-native--canary.518.5269639196.ts)  
[color_sberprime_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.518.5269639196.swift)  
[color_sberprime_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.518.5269639196.kt)  
[color_sberprime_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.518.5269639196.ts)  
[shadow_sbermarket_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.518.5269639196.ts)  
[typo_mage_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.518.5269639196.swift)  
[typo_mage_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.518.5269639196.kt)  
[typo_mage_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.518.5269639196.ts)  
[typo_plasma_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.518.5269639196.swift)  
[typo_plasma_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.518.5269639196.kt)  
[typo_plasma_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.518.5269639196.ts)  
[typo_ruler_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.518.5269639196.swift)  
[typo_ruler_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.518.5269639196.kt)  
[typo_ruler_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.518.5269639196.ts)  
[typo_sage_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.518.5269639196.swift)  
[typo_sage_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.518.5269639196.kt)  
[typo_sage_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.518.5269639196.ts)  
[typo_sbermarket_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.518.5269639196.swift)  
[typo_sbermarket_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.518.5269639196.kt)  
[typo_sbermarket_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.518.5269639196.ts)  
[typo_soulmate_ios-swift--canary.518.5269639196.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.518.5269639196.swift)  
[typo_soulmate_kotlin--canary.518.5269639196.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.518.5269639196.kt)  
[typo_soulmate_react-native--canary.518.5269639196.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.518.5269639196.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.217.0-canary.518.5269639196.0
  npm install @salutejs/plasma-core@1.122.0-canary.518.5269639196.0
  npm install @salutejs/plasma-hope@1.217.0-canary.518.5269639196.0
  npm install @salutejs/plasma-icons@1.151.0-canary.518.5269639196.0
  npm install @salutejs/plasma-temple@1.166.0-canary.518.5269639196.0
  npm install @salutejs/plasma-tokens@1.56.0-canary.518.5269639196.0
  npm install @salutejs/plasma-ui@1.198.0-canary.518.5269639196.0
  npm install @salutejs/plasma-web@1.217.0-canary.518.5269639196.0
  npm install @salutejs/plasma-cy-utils@0.63.0-canary.518.5269639196.0
  npm install @salutejs/plasma-sb-utils@0.120.0-canary.518.5269639196.0
  # or 
  yarn add @salutejs/plasma-b2c@1.217.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-core@1.122.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-hope@1.217.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-icons@1.151.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-temple@1.166.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-tokens@1.56.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-ui@1.198.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-web@1.217.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-cy-utils@0.63.0-canary.518.5269639196.0
  yarn add @salutejs/plasma-sb-utils@0.120.0-canary.518.5269639196.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-518/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-518/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-518/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-518/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-518/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-518/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-518/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-518/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-518/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-518/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-518/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-518/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-518/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-518/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-518/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-518/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-518/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-518/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-518/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-518/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Pull request merged**
