### PR TITLE
fix(plasma-b2c, plasma-web): fix letter-spacing value in Body, Text

### PR DESCRIPTION
**Pull request by kayman233**
Поправлено значение `letter-spacing`(`-0.02em`) во всех для шрифтах `Body`, `Text`. 

Затронутые компоненты:
```
AudioPlayer
Badge
Button
Calendar
Card
Carousel
Cell
Checkbox
Dropdown
Editable
Link
Modal
Notification
PreviewGallery
Price
Progress
Radiobox
Select
Slider
Switch
Tabs
TextField
Toast
Tooltip
Typography
Upload
UploadAudio
UploadVisual
```

Не затронутые:
```
ElasticGrid
Grid
Image
List
PaginationDots
Popup
Skeleton
Spinner
TextArea
```

:baby_chick: Download canary assets:

[color_sberHealth_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.524.5110730752.swift)  
[color_sberHealth_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.524.5110730752.kt)  
[color_sberHealth_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.524.5110730752.ts)  
[color_sbermarket_business_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.524.5110730752.swift)  
[color_sbermarket_business_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.524.5110730752.kt)  
[color_sbermarket_business_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.524.5110730752.ts)  
[color_sbermarket_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.524.5110730752.swift)  
[color_sbermarket_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.524.5110730752.kt)  
[color_sbermarket_metro_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.524.5110730752.swift)  
[color_sbermarket_metro_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.524.5110730752.kt)  
[color_sbermarket_metro_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.524.5110730752.ts)  
[color_sbermarket_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.524.5110730752.ts)  
[color_sbermarket_selgros_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.524.5110730752.swift)  
[color_sbermarket_selgros_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.524.5110730752.kt)  
[color_sbermarket_selgros_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.524.5110730752.ts)  
[color_sbermarket_wlbusiness_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.524.5110730752.swift)  
[color_sbermarket_wlbusiness_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.524.5110730752.kt)  
[color_sbermarket_wlbusiness_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.524.5110730752.ts)  
[color_sberonline_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_ios-swift--canary.524.5110730752.swift)  
[color_sberonline_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_kotlin--canary.524.5110730752.kt)  
[color_sberonline_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_react-native--canary.524.5110730752.ts)  
[color_sberprime_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.524.5110730752.swift)  
[color_sberprime_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.524.5110730752.kt)  
[color_sberprime_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.524.5110730752.ts)  
[shadow_sbermarket_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.524.5110730752.ts)  
[typo_mage_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.524.5110730752.swift)  
[typo_mage_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.524.5110730752.kt)  
[typo_mage_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.524.5110730752.ts)  
[typo_plasma_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.524.5110730752.swift)  
[typo_plasma_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.524.5110730752.kt)  
[typo_plasma_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.524.5110730752.ts)  
[typo_ruler_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.524.5110730752.swift)  
[typo_ruler_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.524.5110730752.kt)  
[typo_ruler_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.524.5110730752.ts)  
[typo_sage_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.524.5110730752.swift)  
[typo_sage_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.524.5110730752.kt)  
[typo_sage_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.524.5110730752.ts)  
[typo_sbermarket_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.524.5110730752.swift)  
[typo_sbermarket_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.524.5110730752.kt)  
[typo_sbermarket_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.524.5110730752.ts)  
[typo_soulmate_ios-swift--canary.524.5110730752.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.524.5110730752.swift)  
[typo_soulmate_kotlin--canary.524.5110730752.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.524.5110730752.kt)  
[typo_soulmate_react-native--canary.524.5110730752.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.524.5110730752.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.215.1-canary.524.5110730752.0
  npm install @salutejs/plasma-core@1.120.1-canary.524.5110730752.0
  npm install @salutejs/plasma-hope@1.215.1-canary.524.5110730752.0
  npm install @salutejs/plasma-icons@1.149.1-canary.524.5110730752.0
  npm install @salutejs/plasma-temple@1.164.1-canary.524.5110730752.0
  npm install @salutejs/plasma-tokens@1.54.1-canary.524.5110730752.0
  npm install @salutejs/plasma-typo@0.33.1-canary.524.5110730752.0
  npm install @salutejs/plasma-ui@1.196.1-canary.524.5110730752.0
  npm install @salutejs/plasma-web@1.215.1-canary.524.5110730752.0
  npm install @salutejs/plasma-cy-utils@0.61.1-canary.524.5110730752.0
  npm install @salutejs/plasma-sb-utils@0.118.1-canary.524.5110730752.0
  # or 
  yarn add @salutejs/plasma-b2c@1.215.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-core@1.120.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-hope@1.215.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-icons@1.149.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-temple@1.164.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-tokens@1.54.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-typo@0.33.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-ui@1.196.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-web@1.215.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-cy-utils@0.61.1-canary.524.5110730752.0
  yarn add @salutejs/plasma-sb-utils@0.118.1-canary.524.5110730752.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-524/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-524/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-524/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-524/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-524/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-524/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-524/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-524/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by Yeti-or — COMMENTED** [review]
Что-то у нас столько изменений, давайте убедимся что мы все верно меняем, и @kayman233 давай это в ветку dev , поменяй просто в настройках pr куда она смотрит

**Review by Yeti-or — APPROVED** [review]
Изменения ориентировочно в следующих компонентах:

```
AudioPlayer
Badge
Button
Calendar
Card
Carousel
Cell
Checkbox
Dropdown
Modal
PreviewGallery
Price
Progress
Radiobox
Select
Slider
Switch
Tabs
TextField
Toast
Tooltip
Typography
Upload
UploadAudio
UploadVisual
```

**Review by Yeti-or — APPROVED** [review]
Изменения ориентировочно в следующих компонентах:

```
AudioPlayer
Badge
Button
Calendar
Card
Carousel
Cell
Checkbox
Dropdown
Modal
PreviewGallery
Price
Progress
Radiobox
Select
Slider
Switch
Tabs
TextField
Toast
Tooltip
Typography
Upload
UploadAudio
UploadVisual
```

**Review by neretin-trike — APPROVED** [review]

**Review by gibushnev — APPROVED** [review]
Ок

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-524/

**Review by Yakutoc — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-524/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-524/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-524/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-524/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-524/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-524/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Pull request merged**
