### PR TITLE
feat(plasma-core): handling button type

### PR DESCRIPTION
**Pull request by Yakutoc**
Для компонента **Button** необходимо установить значение по-умолчанию `"button"` для атрибута `type`.   

:baby_chick: Download canary assets:

[colors--canary.272.3748065397.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.272.3748065397.xml)  
[color_metro_ios-swift--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.272.3748065397.swift)  
[color_metro_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.272.3748065397.kt)  
[color_metro_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.272.3748065397.ts)  
[color_sbermarket_ios-swift--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.272.3748065397.swift)  
[color_sbermarket_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.272.3748065397.kt)  
[color_sbermarket_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.272.3748065397.ts)  
[color_sberprime_ios-swift--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.272.3748065397.swift)  
[color_sberprime_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.272.3748065397.kt)  
[color_sberprime_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.272.3748065397.ts)  
[color_selgros_ios-swift--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.272.3748065397.swift)  
[color_selgros_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.272.3748065397.kt)  
[color_selgros_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.272.3748065397.ts)  
[color_smbusiness_ios-swift--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.272.3748065397.swift)  
[color_smbusiness_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.272.3748065397.kt)  
[color_smbusiness_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.272.3748065397.ts)  
[PlasmaTokensColor--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.272.3748065397.swift)  
[typo_mage_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.272.3748065397.kt)  
[typo_mage_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.272.3748065397.ts)  
[typo_plasma_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.272.3748065397.kt)  
[typo_plasma_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.272.3748065397.ts)  
[typo_ruler_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.272.3748065397.kt)  
[typo_ruler_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.272.3748065397.ts)  
[typo_sage_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.272.3748065397.kt)  
[typo_sage_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.272.3748065397.ts)  
[typo_sbermarket_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.272.3748065397.kt)  
[typo_sbermarket_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.272.3748065397.ts)  
[typo_soulmate_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.272.3748065397.kt)  
[typo_soulmate_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.272.3748065397.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.121.0-canary.272.3748065397.0
  npm install @salutejs/plasma-core@1.87.0-canary.272.3748065397.0
  npm install @salutejs/plasma-icons@1.114.0-canary.272.3748065397.0
  npm install @salutejs/plasma-temple@1.119.0-canary.272.3748065397.0
  npm install @salutejs/plasma-ui@1.152.0-canary.272.3748065397.0
  npm install @salutejs/plasma-web@1.149.0-canary.272.3748065397.0
  npm install @salutejs/plasma-sb-utils@0.85.0-canary.272.3748065397.0
  # or 
  yarn add @salutejs/plasma-b2c@1.121.0-canary.272.3748065397.0
  yarn add @salutejs/plasma-core@1.87.0-canary.272.3748065397.0
  yarn add @salutejs/plasma-icons@1.114.0-canary.272.3748065397.0
  yarn add @salutejs/plasma-temple@1.119.0-canary.272.3748065397.0
  yarn add @salutejs/plasma-ui@1.152.0-canary.272.3748065397.0
  yarn add @salutejs/plasma-web@1.149.0-canary.272.3748065397.0
  yarn add @salutejs/plasma-sb-utils@0.85.0-canary.272.3748065397.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-272/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-272/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-272/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-272/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-272/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-272/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-272/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-272/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-272/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-272/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-272/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-272/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-272/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-272/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-272/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-272/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-272/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-272/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
