### PR TITLE
feat(plasma-temple): grid skeleton

### PR DESCRIPTION
**Pull request by kvpolyanskiy**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.79.0-canary.86.2581627776.0
  # or 
  yarn add @salutejs/plasma-temple@1.79.0-canary.86.2581627776.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-86/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-86/
  ui storybook: http://plasma.sberdevices.ru/pr-86/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-86/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-86/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-86/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-86/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-86/
  ui storybook: http://plasma.sberdevices.ru/pr-86/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-86/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-86/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-86/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-86/

**Review by LamaEats — APPROVED** [review]

**Pull request merged**
