### PR TITLE
feat(perftool): static task stabilizer

### PR DESCRIPTION
**Pull request by akhdrv**
:baby_chick: Download canary assets:

[colors--canary.286.3991984948.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.286.3991984948.xml)  
[color_metro_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.286.3991984948.swift)  
[color_metro_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.286.3991984948.kt)  
[color_metro_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.286.3991984948.ts)  
[color_sbermarket_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.286.3991984948.swift)  
[color_sbermarket_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.286.3991984948.kt)  
[color_sbermarket_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.286.3991984948.ts)  
[color_sberprime_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.286.3991984948.swift)  
[color_sberprime_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.286.3991984948.kt)  
[color_sberprime_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.286.3991984948.ts)  
[color_selgros_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.286.3991984948.swift)  
[color_selgros_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.286.3991984948.kt)  
[color_selgros_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.286.3991984948.ts)  
[color_smbusiness_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.286.3991984948.swift)  
[color_smbusiness_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.286.3991984948.kt)  
[color_smbusiness_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.286.3991984948.ts)  
[PlasmaTokensColor--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.286.3991984948.swift)  
[typo_mage_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.286.3991984948.swift)  
[typo_mage_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.286.3991984948.kt)  
[typo_mage_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.286.3991984948.ts)  
[typo_plasma_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.286.3991984948.swift)  
[typo_plasma_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.286.3991984948.kt)  
[typo_plasma_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.286.3991984948.ts)  
[typo_ruler_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.286.3991984948.swift)  
[typo_ruler_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.286.3991984948.kt)  
[typo_ruler_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.286.3991984948.ts)  
[typo_sage_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.286.3991984948.swift)  
[typo_sage_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.286.3991984948.kt)  
[typo_sage_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.286.3991984948.ts)  
[typo_sbermarket_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.286.3991984948.swift)  
[typo_sbermarket_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.286.3991984948.kt)  
[typo_sbermarket_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.286.3991984948.ts)  
[typo_soulmate_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.286.3991984948.swift)  
[typo_soulmate_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.286.3991984948.kt)  
[typo_soulmate_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.286.3991984948.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.124.0-canary.286.3991984948.0
  npm install @salutejs/plasma-ui@1.157.0-canary.286.3991984948.0
  npm install @salutejs/perftool@0.3.0-canary.286.3991984948.0
  # or 
  yarn add @salutejs/plasma-temple@1.124.0-canary.286.3991984948.0
  yarn add @salutejs/plasma-ui@1.157.0-canary.286.3991984948.0
  yarn add @salutejs/perftool@0.3.0-canary.286.3991984948.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-286/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-286/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-286/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-286/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-286/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-286/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-286/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-286/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-286/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-286/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-286/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-286/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-286/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-286/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-286/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-286/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-286/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-286/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-286/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-286/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-286/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
