### PR TITLE
plasma-icons: add SberSpasibo

### PR DESCRIPTION
**Pull request by Yakutoc**
## Release Notes

Добавлена иконка: 

Screenshot 2023-08-24 at 16 39 45

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.223.0-canary.669.6033062361.0
  npm install @salutejs/plasma-hope@1.223.0-canary.669.6033062361.0
  npm install @salutejs/plasma-icons@1.157.0-canary.669.6033062361.0
  npm install @salutejs/plasma-temple@1.172.0-canary.669.6033062361.0
  npm install @salutejs/plasma-ui@1.204.0-canary.669.6033062361.0
  npm install @salutejs/plasma-web@1.223.0-canary.669.6033062361.0
  # or 
  yarn add @salutejs/plasma-b2c@1.223.0-canary.669.6033062361.0
  yarn add @salutejs/plasma-hope@1.223.0-canary.669.6033062361.0
  yarn add @salutejs/plasma-icons@1.157.0-canary.669.6033062361.0
  yarn add @salutejs/plasma-temple@1.172.0-canary.669.6033062361.0
  yarn add @salutejs/plasma-ui@1.204.0-canary.669.6033062361.0
  yarn add @salutejs/plasma-web@1.223.0-canary.669.6033062361.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-669/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-669/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-669/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-669/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-669/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-669/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-669/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-669/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-669/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-669/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-669/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-669/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-669/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by gibushnev — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-669/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-669/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-669/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-669/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-669/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-669/temple-storybook/

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.223.0-dev.0, @salutejs/plasma-hope@1.223.0-dev.0, @salutejs/plasma-icons@1.157.0-dev.0, @salutejs/plasma-temple@1.172.0-dev.0, @salutejs/plasma-ui@1.204.0-dev.0, @salutejs/plasma-web@1.223.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.225.0-dev.0, @salutejs/plasma-colors@0.10.0-dev.0, @salutejs/plasma-core@1.128.0-dev.0, @salutejs/plasma-cy-utils@0.68.0-dev.0, @salutejs/plasma-hope@1.225.0-dev.0, @salutejs/plasma-icons@1.159.0-dev.0, @salutejs/plasma-sb-utils@0.126.0-dev.0, @salutejs/plasma-temple@1.174.0-dev.0, @salutejs/plasma-tokens-b2b@1.27.0-dev.0, @salutejs/plasma-tokens-b2c@0.36.0-dev.0, @salutejs/plasma-tokens-web@1.42.0-dev.0, @salutejs/plasma-tokens@1.61.0-dev.0, @salutejs/plasma-ui@1.206.0-dev.0, @salutejs/plasma-web@1.225.0-dev.0 🚀

**Pull request merged**
