### PR TITLE
feat(plasma-web): add overlay

### PR DESCRIPTION
**Pull request by Yakutoc**
Для модального окна нужно добавить правильный overlay  с размытием.  

:baby_chick: Download canary assets:

[colors--canary.266.3702515963.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.266.3702515963.xml)  
[color_metro_ios-swift--canary.266.3702515963.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.266.3702515963.swift)  
[color_metro_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.266.3702515963.kt)  
[color_metro_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.266.3702515963.ts)  
[color_sbermarket_ios-swift--canary.266.3702515963.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.266.3702515963.swift)  
[color_sbermarket_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.266.3702515963.kt)  
[color_sbermarket_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.266.3702515963.ts)  
[color_sberprime_ios-swift--canary.266.3702515963.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.266.3702515963.swift)  
[color_sberprime_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.266.3702515963.kt)  
[color_sberprime_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.266.3702515963.ts)  
[color_selgros_ios-swift--canary.266.3702515963.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.266.3702515963.swift)  
[color_selgros_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.266.3702515963.kt)  
[color_selgros_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.266.3702515963.ts)  
[color_smbusiness_ios-swift--canary.266.3702515963.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.266.3702515963.swift)  
[color_smbusiness_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.266.3702515963.kt)  
[color_smbusiness_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.266.3702515963.ts)  
[PlasmaTokensColor--canary.266.3702515963.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.266.3702515963.swift)  
[typo_mage_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.266.3702515963.kt)  
[typo_mage_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.266.3702515963.ts)  
[typo_plasma_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.266.3702515963.kt)  
[typo_plasma_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.266.3702515963.ts)  
[typo_ruler_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.266.3702515963.kt)  
[typo_ruler_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.266.3702515963.ts)  
[typo_sage_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.266.3702515963.kt)  
[typo_sage_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.266.3702515963.ts)  
[typo_sbermarket_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.266.3702515963.kt)  
[typo_sbermarket_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.266.3702515963.ts)  
[typo_soulmate_kotlin--canary.266.3702515963.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.266.3702515963.kt)  
[typo_soulmate_react-native--canary.266.3702515963.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.266.3702515963.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.120.0-canary.266.3702515963.0
  npm install @salutejs/plasma-web@1.148.0-canary.266.3702515963.0
  # or 
  yarn add @salutejs/plasma-b2c@1.120.0-canary.266.3702515963.0
  yarn add @salutejs/plasma-web@1.148.0-canary.266.3702515963.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-266/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-266/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-266/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-266/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-266/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-266/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-266/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-266/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-266/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-266/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-266/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-266/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-266/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-266/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-266/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-266/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-266/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-266/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-266/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-266/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-266/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-266/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-266/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-266/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-266/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-266/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-266/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-266/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-266/temple-storybook/

**Pull request merged**
