### PR TITLE
feat(plasma-b2c): add event as second optional arguments for onChange/onUpload methods

### PR DESCRIPTION
**Pull request by Yakutoc**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.176.3181378209.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.176.3181378209.swift)  
[sbermarket_kotlin--canary.176.3181378209.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.176.3181378209.kt)  
[sbermarket_react-native--canary.176.3181378209.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.176.3181378209.ts)  
[colors--canary.176.3181378209.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.176.3181378209.xml)  
[PlasmaTokensColor--canary.176.3181378209.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.176.3181378209.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.99.0-canary.176.3181378209.0
  # or 
  yarn add @salutejs/plasma-b2c@1.99.0-canary.176.3181378209.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-176/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-176/
  ui storybook: http://plasma.sberdevices.ru/pr-176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-176/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-176/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-176/
  ui storybook: http://plasma.sberdevices.ru/pr-176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-176/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
