### PR TITLE
plasma-infra: Fix manually update deps version in private packages 

### PR DESCRIPTION
**Pull request by Yakutoc**
## Release Notes

Исправлена установка зависимостей для приватных пакетов после публикации RC версии. Версии пакета берется из `lerna ls`

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-687/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-687/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-687/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-687/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-687/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-687/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-687/

**Review by Yeti-or — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-temple@1.175.0-dev.0, @salutejs/plasma-ui@1.207.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-temple@1.175.0-dev.0, @salutejs/plasma-ui@1.207.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-temple@1.175.0-dev.0, @salutejs/plasma-ui@1.207.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-temple@1.175.0-dev.0, @salutejs/plasma-ui@1.207.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.226.0-dev.0, @salutejs/plasma-core@1.129.0-dev.0, @salutejs/plasma-cy-utils@0.69.0-dev.0, @salutejs/plasma-hope@1.226.0-dev.0, @salutejs/plasma-icons@1.160.0-dev.0, @salutejs/plasma-sb-utils@0.127.0-dev.0, @salutejs/plasma-temple@1.176.0-dev.0, @salutejs/plasma-tokens@1.62.0-dev.0, @salutejs/plasma-ui@1.208.0-dev.0, @salutejs/plasma-web@1.226.0-dev.0 🚀

**Pull request merged**
