### PR TITLE
feat(plasma-ui): Add options for eventListeners in useRemoteListener hook

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.90.0-canary.146.2948397596.0
  npm install @salutejs/plasma-ui@1.124.0-canary.146.2948397596.0
  # or 
  yarn add @salutejs/plasma-temple@1.90.0-canary.146.2948397596.0
  yarn add @salutejs/plasma-ui@1.124.0-canary.146.2948397596.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-146/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-146/
  ui storybook: http://plasma.sberdevices.ru/pr-146/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-146/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-146/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-146/temple-storybook/

**Review by takovoy — APPROVED** [review]

**Review by takovoy — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-146/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-146/
  ui storybook: http://plasma.sberdevices.ru/pr-146/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-146/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-146/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-146/temple-storybook/

**Pull request merged**
