### PR TITLE
Fix `Tooltip` behavior with wrapper and Add tooltip in item for `PreviewGallery` component

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.68.0-canary.27.2353193932.0
  npm install @salutejs/plasma-web@1.103.0-canary.27.2353193932.0
  # or 
  yarn add @salutejs/plasma-b2c@1.68.0-canary.27.2353193932.0
  yarn add @salutejs/plasma-web@1.103.0-canary.27.2353193932.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-27/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-27/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-27/
  ui storybook: http://plasma.sberdevices.ru/pr-27/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-27/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-27/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-27/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-27/
  ui storybook: http://plasma.sberdevices.ru/pr-27/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-27/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-27/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-27/temple-storybook/

**Review by kvpolyanskiy — APPROVED** [review]

**Pull request merged**
