### PR TITLE
fix(plasma-tokens-utils): Remove backgroundColor field from theme

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[colors--canary.315.4114146482.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.315.4114146482.xml)  
[color_metro_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.315.4114146482.swift)  
[color_metro_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.315.4114146482.kt)  
[color_metro_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.315.4114146482.ts)  
[color_sbermarket_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.315.4114146482.swift)  
[color_sbermarket_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.315.4114146482.kt)  
[color_sbermarket_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.315.4114146482.ts)  
[color_sberprime_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.315.4114146482.swift)  
[color_sberprime_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.315.4114146482.kt)  
[color_sberprime_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.315.4114146482.ts)  
[color_selgros_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.315.4114146482.swift)  
[color_selgros_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.315.4114146482.kt)  
[color_selgros_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.315.4114146482.ts)  
[color_smbusiness_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.315.4114146482.swift)  
[color_smbusiness_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.315.4114146482.kt)  
[color_smbusiness_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.315.4114146482.ts)  
[PlasmaTokensColor--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.315.4114146482.swift)  
[shadow_sbermarket_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.315.4114146482.ts)  
[typo_mage_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.315.4114146482.swift)  
[typo_mage_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.315.4114146482.kt)  
[typo_mage_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.315.4114146482.ts)  
[typo_plasma_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.315.4114146482.swift)  
[typo_plasma_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.315.4114146482.kt)  
[typo_plasma_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.315.4114146482.ts)  
[typo_ruler_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.315.4114146482.swift)  
[typo_ruler_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.315.4114146482.kt)  
[typo_ruler_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.315.4114146482.ts)  
[typo_sage_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.315.4114146482.swift)  
[typo_sage_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.315.4114146482.kt)  
[typo_sage_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.315.4114146482.ts)  
[typo_sbermarket_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.315.4114146482.swift)  
[typo_sbermarket_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.315.4114146482.kt)  
[typo_sbermarket_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.315.4114146482.ts)  
[typo_soulmate_ios-swift--canary.315.4114146482.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.315.4114146482.swift)  
[typo_soulmate_kotlin--canary.315.4114146482.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.315.4114146482.kt)  
[typo_soulmate_react-native--canary.315.4114146482.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.315.4114146482.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.134.1-canary.315.4114146482.0
  npm install @salutejs/plasma-core@1.92.1-canary.315.4114146482.0
  npm install @salutejs/plasma-icons@1.120.1-canary.315.4114146482.0
  npm install @salutejs/plasma-temple@1.129.1-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens-b2b@1.7.1-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens-b2c@0.16.1-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens-web@1.22.1-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens@1.33.2-canary.315.4114146482.0
  npm install @salutejs/plasma-ui@1.162.1-canary.315.4114146482.0
  npm install @salutejs/plasma-web@1.160.1-canary.315.4114146482.0
  npm install @salutejs/plasma-cy-utils@0.40.2-canary.315.4114146482.0
  npm install @salutejs/plasma-sb-utils@0.90.1-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens-android@2.40.2-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens-ios-swift@2.40.2-canary.315.4114146482.0
  npm install @salutejs/plasma-tokens-utils@0.15.1-canary.315.4114146482.0
  # or 
  yarn add @salutejs/plasma-b2c@1.134.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-core@1.92.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-icons@1.120.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-temple@1.129.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens-b2b@1.7.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens-b2c@0.16.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens-web@1.22.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens@1.33.2-canary.315.4114146482.0
  yarn add @salutejs/plasma-ui@1.162.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-web@1.160.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-cy-utils@0.40.2-canary.315.4114146482.0
  yarn add @salutejs/plasma-sb-utils@0.90.1-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens-android@2.40.2-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.40.2-canary.315.4114146482.0
  yarn add @salutejs/plasma-tokens-utils@0.15.1-canary.315.4114146482.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-315/

**Review by Yeti-or — APPROVED** [review]

**Comment by Yeti-or** [comment]
из plasma-tokens-web оно тоже же исчезнет?

**Comment by neretin-trike** [comment]
> из plasma-tokens-web оно тоже же исчезнет?

да, со всех зависимостей пропадёт

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-315/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-315/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-315/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-315/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-315/temple-storybook/

**Review by Yakutoc — APPROVED** [review]

**Pull request closed without merging**
