### PR TITLE
feat: bump lerna to 4 version

### PR DESCRIPTION
**Pull request by neretin-trike**

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-314/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-314/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-314/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-314/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-314/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-314/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-314/temple-storybook/

**Review by Yakutoc — APPROVED** [review]

**Pull request merged**
