### PR TITLE
refactor(plasma-core): Export "Image" as styled component

### PR DESCRIPTION
**Pull request by Yakutoc**
### Мотивация:

**Уменьшаем кол-во кода**. 

### Было: 

В **plasma-hope/ui** были реализованы свои styled обертки для компонента `Image`

### Стало:

**plasma-core** теперь **экспортирует** styled  обертку. 

:baby_chick: Download canary assets:

[colors--canary.467.4637153343.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.467.4637153343.xml)  
[color_sberHealth_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.467.4637153343.swift)  
[color_sberHealth_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.467.4637153343.kt)  
[color_sberHealth_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.467.4637153343.ts)  
[color_sbermarket_business_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.467.4637153343.swift)  
[color_sbermarket_business_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.467.4637153343.kt)  
[color_sbermarket_business_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.467.4637153343.ts)  
[color_sbermarket_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.467.4637153343.swift)  
[color_sbermarket_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.467.4637153343.kt)  
[color_sbermarket_metro_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.467.4637153343.swift)  
[color_sbermarket_metro_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.467.4637153343.kt)  
[color_sbermarket_metro_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.467.4637153343.ts)  
[color_sbermarket_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.467.4637153343.ts)  
[color_sbermarket_selgros_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.467.4637153343.swift)  
[color_sbermarket_selgros_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.467.4637153343.kt)  
[color_sbermarket_selgros_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.467.4637153343.ts)  
[color_sbermarket_vinlab_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_vinlab_ios-swift--canary.467.4637153343.swift)  
[color_sbermarket_vinlab_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_vinlab_kotlin--canary.467.4637153343.kt)  
[color_sbermarket_vinlab_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_vinlab_react-native--canary.467.4637153343.ts)  
[color_sberprime_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.467.4637153343.swift)  
[color_sberprime_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.467.4637153343.kt)  
[color_sberprime_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.467.4637153343.ts)  
[PlasmaTokensColor--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.467.4637153343.swift)  
[shadow_sbermarket_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.467.4637153343.ts)  
[typo_mage_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.467.4637153343.swift)  
[typo_mage_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.467.4637153343.kt)  
[typo_mage_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.467.4637153343.ts)  
[typo_plasma_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.467.4637153343.swift)  
[typo_plasma_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.467.4637153343.kt)  
[typo_plasma_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.467.4637153343.ts)  
[typo_ruler_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.467.4637153343.swift)  
[typo_ruler_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.467.4637153343.kt)  
[typo_ruler_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.467.4637153343.ts)  
[typo_sage_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.467.4637153343.swift)  
[typo_sage_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.467.4637153343.kt)  
[typo_sage_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.467.4637153343.ts)  
[typo_sbermarket_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.467.4637153343.swift)  
[typo_sbermarket_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.467.4637153343.kt)  
[typo_sbermarket_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.467.4637153343.ts)  
[typo_soulmate_ios-swift--canary.467.4637153343.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.467.4637153343.swift)  
[typo_soulmate_kotlin--canary.467.4637153343.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.467.4637153343.kt)  
[typo_soulmate_react-native--canary.467.4637153343.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.467.4637153343.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.173.3-canary.467.4637153343.0
  npm install @salutejs/plasma-core@1.107.1-canary.467.4637153343.0
  npm install @salutejs/plasma-hope@0.31.3-canary.467.4637153343.0
  npm install @salutejs/plasma-icons@1.136.1-canary.467.4637153343.0
  npm install @salutejs/plasma-temple@1.149.1-canary.467.4637153343.0
  npm install @salutejs/plasma-ui@1.181.1-canary.467.4637153343.0
  npm install @salutejs/plasma-web@1.198.3-canary.467.4637153343.0
  npm install @salutejs/plasma-sb-utils@0.105.1-canary.467.4637153343.0
  # or 
  yarn add @salutejs/plasma-b2c@1.173.3-canary.467.4637153343.0
  yarn add @salutejs/plasma-core@1.107.1-canary.467.4637153343.0
  yarn add @salutejs/plasma-hope@0.31.3-canary.467.4637153343.0
  yarn add @salutejs/plasma-icons@1.136.1-canary.467.4637153343.0
  yarn add @salutejs/plasma-temple@1.149.1-canary.467.4637153343.0
  yarn add @salutejs/plasma-ui@1.181.1-canary.467.4637153343.0
  yarn add @salutejs/plasma-web@1.198.3-canary.467.4637153343.0
  yarn add @salutejs/plasma-sb-utils@0.105.1-canary.467.4637153343.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-467/

**Comment by Yakutoc** [comment]
@neretin-trike @Yeti-or 

Парни помните я задавал вопрос,  а за чем делается **styled обертка** над `Image` ?

Мне тогда объяснили, что иначе мы не можем переопределять стили для этого компонента.

Вот так выглядит обертка: 

```jsx
export const Image: FC<ImageProps> = styled(ImageBase)``;
```

Обратите внимание на **`FC<ImageProps>`** и тогда мы уже не можем сделать 

```jsx
styled.div`
  ${Image} {
     display: none
  }
`
```

Снимок экрана 2023-04-07 в 12 22 59

Судя по всему у нас **всегда** было так. 

Тогда нам нужно или убрать **`FC<ImageProps>`** и править ошибки которые полезут, а они будут.

Или искать другой способ.

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-467/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-467/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-467/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-467/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-467/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-467/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by Yeti-or — COMMENTED** [review]
А почему это feat ? тут же ничего нового не произошло с точки зрения API ?

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-467/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-467/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-467/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-467/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-467/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-467/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-467/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
