### PR TITLE
build: bump lerna to 5.x

### PR DESCRIPTION
**Pull request by Yeti-or**

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-370/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-370/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-370/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-370/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-370/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-370/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-370/temple-storybook/

**Review by Yakutoc — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
