### PR TITLE
plasma-infra: Add `.editorconfig` 

### PR DESCRIPTION
**Pull request by Yakutoc**
## Release Notes

Добавлен:

- `.editorconfig`
- `package.json` в `.prettierignore`  

### What/why Changed

Что бы локальные настройки IDE форматирования не применялись для файлов проекта. 

Для консистентного форматирования добавлен`.editorconfig` и для всех `package.json` сделано **форматирование** с учетом отступа в **4 пробела**. 

Так же добавлено правило `.prettierignore` для `package.json`, что бы `lintstaged` не применял для него форматирование.   

<h3>⚡ Component performance testing</h3>

**Result:** 🟢 OK

<details>
  <summary>:baby_chick: Download canary assets:</summary>
  <blockquote>
    <details>
      <summary>borderRadius</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.837.6807866263.ts'>borderRadius_default_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.837.6807866263.ts'>borderRadius_plasma_b2c_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.837.6807866263.ts'>borderRadius_plasma_web_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sberHealth_react-native--canary.837.6807866263.ts'>borderRadius_sberHealth_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sbermarket_business_react-native--canary.837.6807866263.ts'>borderRadius_sbermarket_business_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sbermarket_metro_react-native--canary.837.6807866263.ts'>borderRadius_sbermarket_metro_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sbermarket_react-native--canary.837.6807866263.ts'>borderRadius_sbermarket_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sbermarket_selgros_react-native--canary.837.6807866263.ts'>borderRadius_sbermarket_selgros_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts'>borderRadius_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sberonline_react-native--canary.837.6807866263.ts'>borderRadius_sberonline_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_sberprime_react-native--canary.837.6807866263.ts'>borderRadius_sberprime_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_stylesSalute_react-native--canary.837.6807866263.ts'>borderRadius_stylesSalute_react-native--canary.837.6807866263.ts</a><br>
      </blockquote>
    </details>
    <details>
      <summary>color</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_ios-swift--canary.837.6807866263.swift'>color_default_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_kotlin--canary.837.6807866263.kt'>color_default_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_react-native--canary.837.6807866263.ts'>color_default_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_xml--canary.837.6807866263.xml'>color_default_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_ios-swift--canary.837.6807866263.swift'>color_plasma_b2c_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_kotlin--canary.837.6807866263.kt'>color_plasma_b2c_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_react-native--canary.837.6807866263.ts'>color_plasma_b2c_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_xml--canary.837.6807866263.xml'>color_plasma_b2c_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_web_ios-swift--canary.837.6807866263.swift'>color_plasma_web_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_web_kotlin--canary.837.6807866263.kt'>color_plasma_web_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_web_react-native--canary.837.6807866263.ts'>color_plasma_web_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_web_xml--canary.837.6807866263.xml'>color_plasma_web_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.837.6807866263.swift'>color_sberHealth_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.837.6807866263.kt'>color_sberHealth_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.837.6807866263.ts'>color_sberHealth_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_xml--canary.837.6807866263.xml'>color_sberHealth_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.837.6807866263.swift'>color_sbermarket_business_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.837.6807866263.kt'>color_sbermarket_business_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.837.6807866263.ts'>color_sbermarket_business_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_xml--canary.837.6807866263.xml'>color_sbermarket_business_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.837.6807866263.swift'>color_sbermarket_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.837.6807866263.kt'>color_sbermarket_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.837.6807866263.swift'>color_sbermarket_metro_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.837.6807866263.kt'>color_sbermarket_metro_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.837.6807866263.ts'>color_sbermarket_metro_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_xml--canary.837.6807866263.xml'>color_sbermarket_metro_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.837.6807866263.ts'>color_sbermarket_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.837.6807866263.swift'>color_sbermarket_selgros_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.837.6807866263.kt'>color_sbermarket_selgros_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.837.6807866263.ts'>color_sbermarket_selgros_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_xml--canary.837.6807866263.xml'>color_sbermarket_selgros_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.837.6807866263.swift'>color_sbermarket_wlbusiness_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.837.6807866263.kt'>color_sbermarket_wlbusiness_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts'>color_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_xml--canary.837.6807866263.xml'>color_sbermarket_wlbusiness_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_xml--canary.837.6807866263.xml'>color_sbermarket_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_ios-swift--canary.837.6807866263.swift'>color_sberonline_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_kotlin--canary.837.6807866263.kt'>color_sberonline_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_react-native--canary.837.6807866263.ts'>color_sberonline_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_xml--canary.837.6807866263.xml'>color_sberonline_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.837.6807866263.swift'>color_sberprime_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.837.6807866263.kt'>color_sberprime_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.837.6807866263.ts'>color_sberprime_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_xml--canary.837.6807866263.xml'>color_sberprime_xml--canary.837.6807866263.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_ios-swift--canary.837.6807866263.swift'>color_stylesSalute_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_kotlin--canary.837.6807866263.kt'>color_stylesSalute_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_react-native--canary.837.6807866263.ts'>color_stylesSalute_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_xml--canary.837.6807866263.xml'>color_stylesSalute_xml--canary.837.6807866263.xml</a><br>
      </blockquote>
    </details>
    <details>
      <summary>shadow</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_default_react-native--canary.837.6807866263.ts'>shadow_default_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_plasma_b2c_react-native--canary.837.6807866263.ts'>shadow_plasma_b2c_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_plasma_web_react-native--canary.837.6807866263.ts'>shadow_plasma_web_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sberHealth_react-native--canary.837.6807866263.ts'>shadow_sberHealth_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_business_react-native--canary.837.6807866263.ts'>shadow_sbermarket_business_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_metro_react-native--canary.837.6807866263.ts'>shadow_sbermarket_metro_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.837.6807866263.ts'>shadow_sbermarket_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_selgros_react-native--canary.837.6807866263.ts'>shadow_sbermarket_selgros_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts'>shadow_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sberonline_react-native--canary.837.6807866263.ts'>shadow_sberonline_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sberprime_react-native--canary.837.6807866263.ts'>shadow_sberprime_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_stylesSalute_react-native--canary.837.6807866263.ts'>shadow_stylesSalute_react-native--canary.837.6807866263.ts</a><br>
      </blockquote>
    </details>
    <details>
      <summary>spacing</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_default_react-native--canary.837.6807866263.ts'>spacing_default_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_plasma_b2c_react-native--canary.837.6807866263.ts'>spacing_plasma_b2c_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_plasma_web_react-native--canary.837.6807866263.ts'>spacing_plasma_web_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sberHealth_react-native--canary.837.6807866263.ts'>spacing_sberHealth_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sbermarket_business_react-native--canary.837.6807866263.ts'>spacing_sbermarket_business_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sbermarket_metro_react-native--canary.837.6807866263.ts'>spacing_sbermarket_metro_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sbermarket_react-native--canary.837.6807866263.ts'>spacing_sbermarket_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sbermarket_selgros_react-native--canary.837.6807866263.ts'>spacing_sbermarket_selgros_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts'>spacing_sbermarket_wlbusiness_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sberonline_react-native--canary.837.6807866263.ts'>spacing_sberonline_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_sberprime_react-native--canary.837.6807866263.ts'>spacing_sberprime_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/spacing_stylesSalute_react-native--canary.837.6807866263.ts'>spacing_stylesSalute_react-native--canary.837.6807866263.ts</a><br>
      </blockquote>
    </details>
    <details>
      <summary>typo</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.837.6807866263.swift'>typo_mage_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.837.6807866263.kt'>typo_mage_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.837.6807866263.ts'>typo_mage_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.837.6807866263.swift'>typo_plasma_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.837.6807866263.kt'>typo_plasma_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.837.6807866263.ts'>typo_plasma_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.837.6807866263.swift'>typo_ruler_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.837.6807866263.kt'>typo_ruler_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.837.6807866263.ts'>typo_ruler_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.837.6807866263.swift'>typo_sage_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.837.6807866263.kt'>typo_sage_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.837.6807866263.ts'>typo_sage_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.837.6807866263.swift'>typo_sbermarket_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.837.6807866263.kt'>typo_sbermarket_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.837.6807866263.ts'>typo_sbermarket_react-native--canary.837.6807866263.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.837.6807866263.swift'>typo_soulmate_ios-swift--canary.837.6807866263.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.837.6807866263.kt'>typo_soulmate_kotlin--canary.837.6807866263.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.837.6807866263.ts'>typo_soulmate_react-native--canary.837.6807866263.ts</a><br>
      </blockquote>
    </details>
  </blockquote>
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-837/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-837/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-837/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-837/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-837/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-837/temple-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-837/new-hope-storybook/

**Review by TitanKuzmich — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/cra-template-plasma-shop-template@2.5.0-dev.0, @salutejs/plasma-asdk@0.2.0-dev.0, @salutejs/plasma-b2c@1.243.0-dev.0, @salutejs/plasma-colors@0.11.0-dev.0, @salutejs/plasma-core@1.138.0-dev.0, @salutejs/plasma-cy-utils@0.72.0-dev.0, @salutejs/plasma-hope@1.241.0-dev.0, @salutejs/plasma-icons@1.170.0-dev.0, @salutejs/plasma-new-hope@0.11.0-dev.0, @salutejs/plasma-sb-utils@0.136.0-dev.0, @salutejs/plasma-temple-docs@0.180.0-dev.0, @salutejs/plasma-temple@1.188.0-dev.0, @salutejs/plasma-tokens-b2b@1.30.0-dev.0, @salutejs/plasma-tokens-b2c@0.39.0-dev.0, @salutejs/plasma-tokens-core@0.5.0-dev.0, @salutejs/plasma-tokens-native@1.15.0-dev.0, @salutejs/plasma-tokens-utils@0.34.0-dev.0, @salutejs/plasma-tokens-web@1.45.0-dev.0, @salutejs/plasma-tokens@1.65.0-dev.0, @salutejs/plasma-typo@0.39.0-dev.0, @salutejs/plasma-ui-docs@0.229.0-dev.0, @salutejs/plasma-ui@1.220.0-dev.0, @salutejs/plasma-web-docs@0.197.0-dev.0, @salutejs/plasma-web@1.243.0-dev.0, @salutejs/plasma-website@0.205.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/cra-template-plasma-shop-template@2.5.0-dev.0, @salutejs/plasma-asdk@0.2.0-dev.0, @salutejs/plasma-b2c@1.243.0-dev.0, @salutejs/plasma-colors@0.11.0-dev.0, @salutejs/plasma-core@1.138.0-dev.0, @salutejs/plasma-cy-utils@0.72.0-dev.0, @salutejs/plasma-hope@1.241.0-dev.0, @salutejs/plasma-icons@1.170.0-dev.0, @salutejs/plasma-new-hope@0.11.0-dev.0, @salutejs/plasma-sb-utils@0.136.0-dev.0, @salutejs/plasma-temple-docs@0.180.0-dev.0, @salutejs/plasma-temple@1.188.0-dev.0, @salutejs/plasma-tokens-b2b@1.30.0-dev.0, @salutejs/plasma-tokens-b2c@0.39.0-dev.0, @salutejs/plasma-tokens-core@0.5.0-dev.0, @salutejs/plasma-tokens-native@1.15.0-dev.0, @salutejs/plasma-tokens-utils@0.34.0-dev.0, @salutejs/plasma-tokens-web@1.45.0-dev.0, @salutejs/plasma-tokens@1.65.0-dev.0, @salutejs/plasma-typo@0.39.0-dev.0, @salutejs/plasma-ui-docs@0.229.0-dev.0, @salutejs/plasma-ui@1.220.0-dev.0, @salutejs/plasma-web-docs@0.197.0-dev.0, @salutejs/plasma-web@1.243.0-dev.0, @salutejs/plasma-website@0.205.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/cra-template-plasma-shop-template@2.5.0-dev.0, @salutejs/plasma-asdk@0.2.0-dev.0, @salutejs/plasma-b2c@1.243.0-dev.0, @salutejs/plasma-colors@0.11.0-dev.0, @salutejs/plasma-core@1.138.0-dev.0, @salutejs/plasma-cy-utils@0.72.0-dev.0, @salutejs/plasma-hope@1.241.0-dev.0, @salutejs/plasma-icons@1.170.0-dev.0, @salutejs/plasma-new-hope@0.11.0-dev.0, @salutejs/plasma-sb-utils@0.136.0-dev.0, @salutejs/plasma-temple-docs@0.180.0-dev.0, @salutejs/plasma-temple@1.188.0-dev.0, @salutejs/plasma-tokens-b2b@1.30.0-dev.0, @salutejs/plasma-tokens-b2c@0.39.0-dev.0, @salutejs/plasma-tokens-core@0.5.0-dev.0, @salutejs/plasma-tokens-native@1.15.0-dev.0, @salutejs/plasma-tokens-utils@0.34.0-dev.0, @salutejs/plasma-tokens-web@1.45.0-dev.0, @salutejs/plasma-tokens@1.65.0-dev.0, @salutejs/plasma-typo@0.39.0-dev.0, @salutejs/plasma-ui-docs@0.229.0-dev.0, @salutejs/plasma-ui@1.220.0-dev.0, @salutejs/plasma-web-docs@0.197.0-dev.0, @salutejs/plasma-web@1.243.0-dev.0, @salutejs/plasma-website@0.205.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/cra-template-plasma-shop-template@2.5.0-dev.0, @salutejs/plasma-asdk@0.2.0-dev.0, @salutejs/plasma-b2c@1.243.0-dev.0, @salutejs/plasma-colors@0.11.0-dev.0, @salutejs/plasma-core@1.138.0-dev.0, @salutejs/plasma-cy-utils@0.72.0-dev.0, @salutejs/plasma-hope@1.241.0-dev.0, @salutejs/plasma-icons@1.170.0-dev.0, @salutejs/plasma-new-hope@0.11.0-dev.0, @salutejs/plasma-sb-utils@0.136.0-dev.0, @salutejs/plasma-temple-docs@0.180.0-dev.0, @salutejs/plasma-temple@1.188.0-dev.0, @salutejs/plasma-tokens-b2b@1.30.0-dev.0, @salutejs/plasma-tokens-b2c@0.39.0-dev.0, @salutejs/plasma-tokens-core@0.5.0-dev.0, @salutejs/plasma-tokens-native@1.15.0-dev.0, @salutejs/plasma-tokens-utils@0.34.0-dev.0, @salutejs/plasma-tokens-web@1.45.0-dev.0, @salutejs/plasma-tokens@1.65.0-dev.0, @salutejs/plasma-typo@0.39.0-dev.0, @salutejs/plasma-ui-docs@0.229.0-dev.0, @salutejs/plasma-ui@1.220.0-dev.0, @salutejs/plasma-web-docs@0.197.0-dev.0, @salutejs/plasma-web@1.243.0-dev.0, @salutejs/plasma-website@0.205.0-dev.0 🚀

**Pull request merged**
