### PR TITLE
fix(plasma-temple): fix warnings and rerender of HeroSlider

### PR DESCRIPTION
**Pull request by LamaEats**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.196.3336411635.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.196.3336411635.swift)  
[sbermarket_kotlin--canary.196.3336411635.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.196.3336411635.kt)  
[sbermarket_react-native--canary.196.3336411635.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.196.3336411635.ts)  
[sberprime_ios-swift--canary.196.3336411635.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.196.3336411635.swift)  
[sberprime_kotlin--canary.196.3336411635.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_kotlin--canary.196.3336411635.kt)  
[sberprime_react-native--canary.196.3336411635.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_react-native--canary.196.3336411635.ts)  
[colors--canary.196.3336411635.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.196.3336411635.xml)  
[PlasmaTokensColor--canary.196.3336411635.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.196.3336411635.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.106.2-canary.196.3336411635.0
  npm install @salutejs/plasma-core@1.78.1-canary.196.3336411635.0
  npm install @salutejs/plasma-icons@1.103.2-canary.196.3336411635.0
  npm install @salutejs/plasma-temple@1.105.1-canary.196.3336411635.0
  npm install @salutejs/plasma-typo@0.25.1-canary.196.3336411635.0
  npm install @salutejs/plasma-ui@1.139.1-canary.196.3336411635.0
  npm install @salutejs/plasma-web@1.137.2-canary.196.3336411635.0
  npm install @salutejs/plasma-cy-utils@0.31.1-canary.196.3336411635.0
  npm install @salutejs/plasma-sb-utils@0.76.2-canary.196.3336411635.0
  # or 
  yarn add @salutejs/plasma-b2c@1.106.2-canary.196.3336411635.0
  yarn add @salutejs/plasma-core@1.78.1-canary.196.3336411635.0
  yarn add @salutejs/plasma-icons@1.103.2-canary.196.3336411635.0
  yarn add @salutejs/plasma-temple@1.105.1-canary.196.3336411635.0
  yarn add @salutejs/plasma-typo@0.25.1-canary.196.3336411635.0
  yarn add @salutejs/plasma-ui@1.139.1-canary.196.3336411635.0
  yarn add @salutejs/plasma-web@1.137.2-canary.196.3336411635.0
  yarn add @salutejs/plasma-cy-utils@0.31.1-canary.196.3336411635.0
  yarn add @salutejs/plasma-sb-utils@0.76.2-canary.196.3336411635.0
  ```
</details>

### CODE REVIEW

**Review by Yeti-or — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-196/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-196/
  ui storybook: http://plasma.sberdevices.ru/pr-196/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-196/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-196/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-196/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-196/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-196/
  ui storybook: http://plasma.sberdevices.ru/pr-196/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-196/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-196/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-196/temple-storybook/

**Pull request merged**
