### PR TITLE
ci: new endpoint for perftool-send-report

### PR DESCRIPTION
**Pull request by akhdrv**
Обновляет ручку отправки отчетов перфтула. Меняет имена полей, добавляет referrer (PR url)
Тест в https://github.com/salute-developers/plasma/pull/731

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-730/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-730/

**Review by Yeti-or — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Review by Yakutoc — APPROVED** [review]

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-new-hope@0.1.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-new-hope@0.1.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.228.0-dev.0, @salutejs/plasma-core@1.131.0-dev.0, @salutejs/plasma-hope@1.228.0-dev.0, @salutejs/plasma-icons@1.162.0-dev.0, @salutejs/plasma-sb-utils@0.129.0-dev.0, @salutejs/plasma-temple-docs@0.165.0-dev.0, @salutejs/plasma-temple@1.179.0-dev.0, @salutejs/plasma-ui-docs@0.214.0-dev.0, @salutejs/plasma-ui@1.211.0-dev.0, @salutejs/plasma-web-docs@0.182.0-dev.0, @salutejs/plasma-web@1.228.0-dev.0, @salutejs/plasma-website@0.190.0-dev.0 🚀

**Pull request merged**
