### PR TITLE
feat(plasma-temple): add `renderText` prop for `StateLayout` component

### PR DESCRIPTION
**Pull request by LamaEats**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.168.3203069500.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.168.3203069500.swift)  
[sbermarket_kotlin--canary.168.3203069500.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.168.3203069500.kt)  
[sbermarket_react-native--canary.168.3203069500.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.168.3203069500.ts)  
[colors--canary.168.3203069500.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.168.3203069500.xml)  
[PlasmaTokensColor--canary.168.3203069500.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.168.3203069500.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.102.0-canary.168.3203069500.0
  # or 
  yarn add @salutejs/plasma-temple@1.102.0-canary.168.3203069500.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-168/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-168/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-168/
  ui storybook: http://plasma.sberdevices.ru/pr-168/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-168/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-168/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-168/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-168/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-168/
  ui storybook: http://plasma.sberdevices.ru/pr-168/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-168/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-168/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-168/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-168/
  ui storybook: http://plasma.sberdevices.ru/pr-168/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-168/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-168/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-168/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
