### PR TITLE
feat(plasma-tokens-utils): Add data selector for generated theme

### PR DESCRIPTION
**Pull request by neretin-trike**
Были добавлены новые селекторы для сгенерированных тем:

image

:baby_chick: Download canary assets:

[colors--canary.481.4686380999.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.481.4686380999.xml)  
[color_sberHealth_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.481.4686380999.swift)  
[color_sberHealth_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.481.4686380999.kt)  
[color_sberHealth_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.481.4686380999.ts)  
[color_sbermarket_business_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.481.4686380999.swift)  
[color_sbermarket_business_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.481.4686380999.kt)  
[color_sbermarket_business_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.481.4686380999.ts)  
[color_sbermarket_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.481.4686380999.swift)  
[color_sbermarket_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.481.4686380999.kt)  
[color_sbermarket_metro_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.481.4686380999.swift)  
[color_sbermarket_metro_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.481.4686380999.kt)  
[color_sbermarket_metro_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.481.4686380999.ts)  
[color_sbermarket_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.481.4686380999.ts)  
[color_sbermarket_selgros_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.481.4686380999.swift)  
[color_sbermarket_selgros_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.481.4686380999.kt)  
[color_sbermarket_selgros_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.481.4686380999.ts)  
[color_sbermarket_vinlab_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_vinlab_ios-swift--canary.481.4686380999.swift)  
[color_sbermarket_vinlab_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_vinlab_kotlin--canary.481.4686380999.kt)  
[color_sbermarket_vinlab_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_vinlab_react-native--canary.481.4686380999.ts)  
[color_sberprime_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.481.4686380999.swift)  
[color_sberprime_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.481.4686380999.kt)  
[color_sberprime_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.481.4686380999.ts)  
[PlasmaTokensColor--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.481.4686380999.swift)  
[shadow_sbermarket_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.481.4686380999.ts)  
[typo_mage_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.481.4686380999.swift)  
[typo_mage_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.481.4686380999.kt)  
[typo_mage_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.481.4686380999.ts)  
[typo_plasma_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.481.4686380999.swift)  
[typo_plasma_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.481.4686380999.kt)  
[typo_plasma_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.481.4686380999.ts)  
[typo_ruler_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.481.4686380999.swift)  
[typo_ruler_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.481.4686380999.kt)  
[typo_ruler_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.481.4686380999.ts)  
[typo_sage_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.481.4686380999.swift)  
[typo_sage_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.481.4686380999.kt)  
[typo_sage_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.481.4686380999.ts)  
[typo_sbermarket_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.481.4686380999.swift)  
[typo_sbermarket_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.481.4686380999.kt)  
[typo_sbermarket_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.481.4686380999.ts)  
[typo_soulmate_ios-swift--canary.481.4686380999.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.481.4686380999.swift)  
[typo_soulmate_kotlin--canary.481.4686380999.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.481.4686380999.kt)  
[typo_soulmate_react-native--canary.481.4686380999.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.481.4686380999.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.175.0-canary.481.4686380999.0
  npm install @salutejs/plasma-core@1.109.0-canary.481.4686380999.0
  npm install @salutejs/plasma-hope@0.33.0-canary.481.4686380999.0
  npm install @salutejs/plasma-icons@1.138.0-canary.481.4686380999.0
  npm install @salutejs/plasma-temple@1.151.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens-b2b@1.15.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens-b2c@0.24.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens-web@1.30.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens@1.45.0-canary.481.4686380999.0
  npm install @salutejs/plasma-ui@1.183.0-canary.481.4686380999.0
  npm install @salutejs/plasma-web@1.200.0-canary.481.4686380999.0
  npm install @salutejs/plasma-cy-utils@0.52.0-canary.481.4686380999.0
  npm install @salutejs/plasma-sb-utils@0.107.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens-android@2.52.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens-ios-swift@2.52.0-canary.481.4686380999.0
  npm install @salutejs/plasma-tokens-utils@0.21.0-canary.481.4686380999.0
  # or 
  yarn add @salutejs/plasma-b2c@1.175.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-core@1.109.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-hope@0.33.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-icons@1.138.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-temple@1.151.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens-b2b@1.15.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens-b2c@0.24.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens-web@1.30.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens@1.45.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-ui@1.183.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-web@1.200.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-cy-utils@0.52.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-sb-utils@0.107.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens-android@2.52.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.52.0-canary.481.4686380999.0
  yarn add @salutejs/plasma-tokens-utils@0.21.0-canary.481.4686380999.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-481/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-481/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-481/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-481/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-481/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-481/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-481/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Comment by Yakutoc** [comment]
@neretin-trike Добавь пожалуйста было/стало и почему так сделали.

**Review by Yakutoc — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Comment by neretin-trike** [comment]
> а есть codesanbox где показано как это работает ?

неа, codesanbox не собирал, т.к. наши компоненты всё-равно пока не работают с новой схемой. Но я прикрепил скриншот в шапке того, как это выглядит после билда

**Pull request closed without merging**
