### PR TITLE
feat(plasma-tokens-web/b2b/b2c/ui): Add overlay tokens

### PR DESCRIPTION
**Pull request by Yakutoc**
Добавляем новые токены для overlay в **plasma-tokens/-web/-b2c/-b2b**

Команда `npm run build` выдает результат для новых токенов: 

```js
exports.overlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.overlayHard = 'rgba(8, 8, 8, 0.9)';
exports.overlayBlur = 'rgba(35, 35, 35, 0.2)';
exports.darkOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.darkOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.darkOverlayBlur = 'rgba(35, 35, 35, 0.2)';
exports.lightOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.lightOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.lightOverlayBlur = 'rgba(35, 35, 35, 0.28)';
exports.inverseOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.inverseOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.inverseOverlayBlur = 'rgba(35, 35, 35, 0.28)';
``` 
  
```css
"--plasma-colors-overlaySoft": "rgba(8, 8, 8, 0.56)",
 "--plasma-colors-overlayHard": "rgba(8, 8, 8, 0.9)",
"--plasma-colors-overlayBlur": "rgba(35, 35, 35, 0.2)",
"--plasma-colors-darkOverlaySoft": "rgba(8, 8, 8, 0.56)",
 "--plasma-colors-darkOverlayHard": "rgba(8, 8, 8, 0.9)",
"--plasma-colors-darkOverlayBlur": "rgba(35, 35, 35, 0.2)",
"--plasma-colors-lightOverlaySoft": "rgba(8, 8, 8, 0.56)",
"--plasma-colors-lightOverlayHard": "rgba(8, 8, 8, 0.9)",
"--plasma-colors-lightOverlayBlur": "rgba(35, 35, 35, 0.28)",
"--plasma-colors-inverseOverlaySoft": "rgba(8, 8, 8, 0.56)",
"--plasma-colors-inverseOverlayHard": "rgba(8, 8, 8, 0.9)",
"--plasma-colors-inverseOverlayBlur": "rgba(35, 35, 35, 0.28)",
```

**NOTE:** Комментарии для новых токенов пока не добавляем. Согласовано с @gibushnev.
  

:baby_chick: Download canary assets:

[colors--canary.256.3636525637.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.256.3636525637.xml)  
[color_sbermarket_ios-swift--canary.256.3636525637.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.256.3636525637.swift)  
[color_sbermarket_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.256.3636525637.kt)  
[color_sbermarket_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.256.3636525637.ts)  
[color_sberprime_ios-swift--canary.256.3636525637.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.256.3636525637.swift)  
[color_sberprime_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.256.3636525637.kt)  
[color_sberprime_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.256.3636525637.ts)  
[PlasmaTokensColor--canary.256.3636525637.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.256.3636525637.swift)  
[typo_mage_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.256.3636525637.kt)  
[typo_mage_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.256.3636525637.ts)  
[typo_plasma_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.256.3636525637.kt)  
[typo_plasma_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.256.3636525637.ts)  
[typo_ruler_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.256.3636525637.kt)  
[typo_ruler_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.256.3636525637.ts)  
[typo_sage_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.256.3636525637.kt)  
[typo_sage_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.256.3636525637.ts)  
[typo_sbermarket_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.256.3636525637.kt)  
[typo_sbermarket_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.256.3636525637.ts)  
[typo_soulmate_kotlin--canary.256.3636525637.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.256.3636525637.kt)  
[typo_soulmate_react-native--canary.256.3636525637.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.256.3636525637.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.117.0-canary.256.3636525637.0
  npm install @salutejs/plasma-core@1.84.0-canary.256.3636525637.0
  npm install @salutejs/plasma-icons@1.111.0-canary.256.3636525637.0
  npm install @salutejs/plasma-temple@1.115.0-canary.256.3636525637.0
  npm install @salutejs/plasma-tokens-b2b@1.5.0-canary.256.3636525637.0
  npm install @salutejs/plasma-tokens-b2c@0.14.0-canary.256.3636525637.0
  npm install @salutejs/plasma-tokens-web@1.20.0-canary.256.3636525637.0
  npm install @salutejs/plasma-tokens@1.29.0-canary.256.3636525637.0
  npm install @salutejs/plasma-ui@1.148.0-canary.256.3636525637.0
  npm install @salutejs/plasma-web@1.145.0-canary.256.3636525637.0
  npm install @salutejs/plasma-cy-utils@0.35.0-canary.256.3636525637.0
  npm install @salutejs/plasma-sb-utils@0.82.0-canary.256.3636525637.0
  npm install @salutejs/plasma-tokens-android@2.36.0-canary.256.3636525637.0
  npm install @salutejs/plasma-tokens-ios-swift@2.36.0-canary.256.3636525637.0
  # or 
  yarn add @salutejs/plasma-b2c@1.117.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-core@1.84.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-icons@1.111.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-temple@1.115.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-tokens-b2b@1.5.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-tokens-b2c@0.14.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-tokens-web@1.20.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-tokens@1.29.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-ui@1.148.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-web@1.145.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-cy-utils@0.35.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-sb-utils@0.82.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-tokens-android@2.36.0-canary.256.3636525637.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.36.0-canary.256.3636525637.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-256/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-256/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-256/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-256/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-256/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-256/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-256/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-256/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-256/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-256/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-256/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-256/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-256/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-256/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-256/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-256/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-256/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-256/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
