### PR TITLE
fix(plasma-ui): restore scroll in translateToIndex

### PR DESCRIPTION
**Pull request by arsenykruglikov**
:baby_chick: Download canary assets:

[colors--canary.162.3045568868.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.162.3045568868.xml)  
[PlasmaTokensColor--canary.162.3045568868.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.162.3045568868.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.93.1-canary.162.3045568868.0
  npm install @salutejs/plasma-core@1.70.1-canary.162.3045568868.0
  npm install @salutejs/plasma-icons@1.96.1-canary.162.3045568868.0
  npm install @salutejs/plasma-temple@1.93.1-canary.162.3045568868.0
  npm install @salutejs/plasma-typo@0.17.1-canary.162.3045568868.0
  npm install @salutejs/plasma-ui@1.127.1-canary.162.3045568868.0
  npm install @salutejs/plasma-web@1.126.1-canary.162.3045568868.0
  npm install @salutejs/plasma-cy-utils@0.23.1-canary.162.3045568868.0
  npm install @salutejs/plasma-sb-utils@0.69.1-canary.162.3045568868.0
  # or 
  yarn add @salutejs/plasma-b2c@1.93.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-core@1.70.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-icons@1.96.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-temple@1.93.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-typo@0.17.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-ui@1.127.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-web@1.126.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-cy-utils@0.23.1-canary.162.3045568868.0
  yarn add @salutejs/plasma-sb-utils@0.69.1-canary.162.3045568868.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-162/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-162/
  ui storybook: http://plasma.sberdevices.ru/pr-162/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-162/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-162/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-162/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-162/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-162/
  ui storybook: http://plasma.sberdevices.ru/pr-162/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-162/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-162/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-162/temple-storybook/

**Review by KateKate — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
