### PR TITLE
fix(plasma-ui): fixes CarouselLite short track scroll bug

### PR DESCRIPTION
**Pull request by arsenykruglikov**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.184.3218763047.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.184.3218763047.swift)  
[sbermarket_kotlin--canary.184.3218763047.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.184.3218763047.kt)  
[sbermarket_react-native--canary.184.3218763047.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.184.3218763047.ts)  
[colors--canary.184.3218763047.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.184.3218763047.xml)  
[PlasmaTokensColor--canary.184.3218763047.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.184.3218763047.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.102.2-canary.184.3218763047.0
  npm install @salutejs/plasma-core@1.76.2-canary.184.3218763047.0
  npm install @salutejs/plasma-icons@1.102.2-canary.184.3218763047.0
  npm install @salutejs/plasma-temple@1.102.2-canary.184.3218763047.0
  npm install @salutejs/plasma-typo@0.23.2-canary.184.3218763047.0
  npm install @salutejs/plasma-ui@1.136.2-canary.184.3218763047.0
  npm install @salutejs/plasma-web@1.134.2-canary.184.3218763047.0
  npm install @salutejs/plasma-cy-utils@0.29.2-canary.184.3218763047.0
  npm install @salutejs/plasma-sb-utils@0.75.2-canary.184.3218763047.0
  # or 
  yarn add @salutejs/plasma-b2c@1.102.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-core@1.76.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-icons@1.102.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-temple@1.102.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-typo@0.23.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-ui@1.136.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-web@1.134.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-cy-utils@0.29.2-canary.184.3218763047.0
  yarn add @salutejs/plasma-sb-utils@0.75.2-canary.184.3218763047.0
  ```
</details>

### CODE REVIEW

**Review by KateKate — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-184/

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-184/
  ui storybook: http://plasma.sberdevices.ru/pr-184/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-184/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-184/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-184/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-184/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-184/
  ui storybook: http://plasma.sberdevices.ru/pr-184/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-184/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-184/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-184/temple-storybook/

**Pull request merged**
