### PR TITLE
fix(plasma-web, plasma-b2c): h5 font-size fix

### PR DESCRIPTION
**Pull request by kayman233**
Поправлены размеры шрифта для H5, для которого поменялось значение на маленьких экранах (`14px` -> `16px`)

<details>
  <summary>:baby_chick: Download canary assets:</summary>
  <blockquote>
    <details>
      <summary>color</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_ios-swift--canary.633.5691345013.swift'>color_plasma_b2c_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_kotlin--canary.633.5691345013.kt'>color_plasma_b2c_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_react-native--canary.633.5691345013.ts'>color_plasma_b2c_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_xml--canary.633.5691345013.xml'>color_plasma_b2c_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.633.5691345013.swift'>color_sberHealth_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.633.5691345013.kt'>color_sberHealth_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.633.5691345013.ts'>color_sberHealth_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_xml--canary.633.5691345013.xml'>color_sberHealth_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.633.5691345013.swift'>color_sbermarket_business_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.633.5691345013.kt'>color_sbermarket_business_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.633.5691345013.ts'>color_sbermarket_business_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_xml--canary.633.5691345013.xml'>color_sbermarket_business_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.633.5691345013.swift'>color_sbermarket_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.633.5691345013.kt'>color_sbermarket_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.633.5691345013.swift'>color_sbermarket_metro_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.633.5691345013.kt'>color_sbermarket_metro_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.633.5691345013.ts'>color_sbermarket_metro_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_xml--canary.633.5691345013.xml'>color_sbermarket_metro_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.633.5691345013.ts'>color_sbermarket_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.633.5691345013.swift'>color_sbermarket_selgros_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.633.5691345013.kt'>color_sbermarket_selgros_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.633.5691345013.ts'>color_sbermarket_selgros_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_xml--canary.633.5691345013.xml'>color_sbermarket_selgros_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.633.5691345013.swift'>color_sbermarket_wlbusiness_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.633.5691345013.kt'>color_sbermarket_wlbusiness_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.633.5691345013.ts'>color_sbermarket_wlbusiness_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_xml--canary.633.5691345013.xml'>color_sbermarket_wlbusiness_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_xml--canary.633.5691345013.xml'>color_sbermarket_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_ios-swift--canary.633.5691345013.swift'>color_sberonline_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_kotlin--canary.633.5691345013.kt'>color_sberonline_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_react-native--canary.633.5691345013.ts'>color_sberonline_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_xml--canary.633.5691345013.xml'>color_sberonline_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.633.5691345013.swift'>color_sberprime_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.633.5691345013.kt'>color_sberprime_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.633.5691345013.ts'>color_sberprime_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_xml--canary.633.5691345013.xml'>color_sberprime_xml--canary.633.5691345013.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_ios-swift--canary.633.5691345013.swift'>color_stylesSalute_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_kotlin--canary.633.5691345013.kt'>color_stylesSalute_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_react-native--canary.633.5691345013.ts'>color_stylesSalute_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_stylesSalute_xml--canary.633.5691345013.xml'>color_stylesSalute_xml--canary.633.5691345013.xml</a><br>
      </blockquote>
    </details>
    <details>
      <summary>shadow</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_plasma_b2c_react-native--canary.633.5691345013.ts'>shadow_plasma_b2c_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sberHealth_react-native--canary.633.5691345013.ts'>shadow_sberHealth_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_business_react-native--canary.633.5691345013.ts'>shadow_sbermarket_business_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_metro_react-native--canary.633.5691345013.ts'>shadow_sbermarket_metro_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.633.5691345013.ts'>shadow_sbermarket_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_selgros_react-native--canary.633.5691345013.ts'>shadow_sbermarket_selgros_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_wlbusiness_react-native--canary.633.5691345013.ts'>shadow_sbermarket_wlbusiness_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sberonline_react-native--canary.633.5691345013.ts'>shadow_sberonline_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sberprime_react-native--canary.633.5691345013.ts'>shadow_sberprime_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_stylesSalute_react-native--canary.633.5691345013.ts'>shadow_stylesSalute_react-native--canary.633.5691345013.ts</a><br>
      </blockquote>
    </details>
    <details>
      <summary>typo</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.633.5691345013.swift'>typo_mage_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.633.5691345013.kt'>typo_mage_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.633.5691345013.ts'>typo_mage_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.633.5691345013.swift'>typo_plasma_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.633.5691345013.kt'>typo_plasma_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.633.5691345013.ts'>typo_plasma_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.633.5691345013.swift'>typo_ruler_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.633.5691345013.kt'>typo_ruler_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.633.5691345013.ts'>typo_ruler_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.633.5691345013.swift'>typo_sage_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.633.5691345013.kt'>typo_sage_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.633.5691345013.ts'>typo_sage_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.633.5691345013.swift'>typo_sbermarket_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.633.5691345013.kt'>typo_sbermarket_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.633.5691345013.ts'>typo_sbermarket_react-native--canary.633.5691345013.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.633.5691345013.swift'>typo_soulmate_ios-swift--canary.633.5691345013.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.633.5691345013.kt'>typo_soulmate_kotlin--canary.633.5691345013.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.633.5691345013.ts'>typo_soulmate_react-native--canary.633.5691345013.ts</a><br>
      </blockquote>
    </details>
  </blockquote>
</details>

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.219.1-canary.633.5691345013.0
  npm install @salutejs/plasma-core@1.124.1-canary.633.5691345013.0
  npm install @salutejs/plasma-hope@1.219.1-canary.633.5691345013.0
  npm install @salutejs/plasma-icons@1.153.1-canary.633.5691345013.0
  npm install @salutejs/plasma-temple@1.168.1-canary.633.5691345013.0
  npm install @salutejs/plasma-tokens-b2b@1.23.1-canary.633.5691345013.0
  npm install @salutejs/plasma-tokens-b2c@0.32.1-canary.633.5691345013.0
  npm install @salutejs/plasma-tokens-web@1.38.1-canary.633.5691345013.0
  npm install @salutejs/plasma-tokens@1.57.1-canary.633.5691345013.0
  npm install @salutejs/plasma-typo@0.35.1-canary.633.5691345013.0
  npm install @salutejs/plasma-ui@1.200.1-canary.633.5691345013.0
  npm install @salutejs/plasma-web@1.219.1-canary.633.5691345013.0
  npm install @salutejs/plasma-cy-utils@0.64.1-canary.633.5691345013.0
  npm install @salutejs/plasma-sb-utils@0.122.1-canary.633.5691345013.0
  npm install @salutejs/plasma-tokens-utils@0.28.1-canary.633.5691345013.0
  # or 
  yarn add @salutejs/plasma-b2c@1.219.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-core@1.124.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-hope@1.219.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-icons@1.153.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-temple@1.168.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-tokens-b2b@1.23.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-tokens-b2c@0.32.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-tokens-web@1.38.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-tokens@1.57.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-typo@0.35.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-ui@1.200.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-web@1.219.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-cy-utils@0.64.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-sb-utils@0.122.1-canary.633.5691345013.0
  yarn add @salutejs/plasma-tokens-utils@0.28.1-canary.633.5691345013.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-633/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-633/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-633/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-633/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-633/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-633/temple-storybook/

**Comment by Yakutoc** [comment]
@kayman233 А с чем связанны эти изменения? Немного контекста пожалуйста )

**Comment by kayman233** [comment]
> @kayman233 А с чем связанны эти изменения? Немного контекста пожалуйста )

добавил в описании

**Review by Yakutoc — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-633/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-633/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-633/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-633/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-633/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-633/temple-storybook/

**Pull request merged**
