### PR TITLE
feat(plasma-web): add accent color for Progress

### PR DESCRIPTION
**Pull request by Yakutoc**
Необходимо добавить для компонента Progress цвет accent

:baby_chick: Download canary assets:

[colors--canary.260.3647499364.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.260.3647499364.xml)  
[color_metro_ios-swift--canary.260.3647499364.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.260.3647499364.swift)  
[color_metro_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.260.3647499364.kt)  
[color_metro_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.260.3647499364.ts)  
[color_sbermarket_ios-swift--canary.260.3647499364.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.260.3647499364.swift)  
[color_sbermarket_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.260.3647499364.kt)  
[color_sbermarket_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.260.3647499364.ts)  
[color_sberprime_ios-swift--canary.260.3647499364.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.260.3647499364.swift)  
[color_sberprime_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.260.3647499364.kt)  
[color_sberprime_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.260.3647499364.ts)  
[color_selgros_ios-swift--canary.260.3647499364.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.260.3647499364.swift)  
[color_selgros_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.260.3647499364.kt)  
[color_selgros_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.260.3647499364.ts)  
[color_smbusiness_ios-swift--canary.260.3647499364.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.260.3647499364.swift)  
[color_smbusiness_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.260.3647499364.kt)  
[color_smbusiness_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.260.3647499364.ts)  
[PlasmaTokensColor--canary.260.3647499364.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.260.3647499364.swift)  
[typo_mage_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.260.3647499364.kt)  
[typo_mage_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.260.3647499364.ts)  
[typo_plasma_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.260.3647499364.kt)  
[typo_plasma_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.260.3647499364.ts)  
[typo_ruler_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.260.3647499364.kt)  
[typo_ruler_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.260.3647499364.ts)  
[typo_sage_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.260.3647499364.kt)  
[typo_sage_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.260.3647499364.ts)  
[typo_sbermarket_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.260.3647499364.kt)  
[typo_sbermarket_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.260.3647499364.ts)  
[typo_soulmate_kotlin--canary.260.3647499364.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.260.3647499364.kt)  
[typo_soulmate_react-native--canary.260.3647499364.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.260.3647499364.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.117.0-canary.260.3647499364.0
  npm install @salutejs/plasma-core@1.84.0-canary.260.3647499364.0
  npm install @salutejs/plasma-icons@1.111.0-canary.260.3647499364.0
  npm install @salutejs/plasma-temple@1.116.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens-b2b@1.5.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens-b2c@0.14.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens-web@1.20.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens@1.29.0-canary.260.3647499364.0
  npm install @salutejs/plasma-ui@1.149.0-canary.260.3647499364.0
  npm install @salutejs/plasma-web@1.145.0-canary.260.3647499364.0
  npm install @salutejs/plasma-cy-utils@0.35.0-canary.260.3647499364.0
  npm install @salutejs/plasma-sb-utils@0.82.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens-android@2.36.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens-ios-swift@2.36.0-canary.260.3647499364.0
  npm install @salutejs/plasma-tokens-utils@0.14.0-canary.260.3647499364.0
  # or 
  yarn add @salutejs/plasma-b2c@1.117.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-core@1.84.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-icons@1.111.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-temple@1.116.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens-b2b@1.5.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens-b2c@0.14.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens-web@1.20.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens@1.29.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-ui@1.149.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-web@1.145.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-cy-utils@0.35.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-sb-utils@0.82.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens-android@2.36.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.36.0-canary.260.3647499364.0
  yarn add @salutejs/plasma-tokens-utils@0.14.0-canary.260.3647499364.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-260/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-260/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-260/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-260/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-260/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-260/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-260/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-260/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-260/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-260/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-260/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-260/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
