### PR TITLE
fix(plasma-temple): update `HeroSliderDots` component

### PR DESCRIPTION
**Pull request by LamaEats**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.202.3337683697.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.202.3337683697.swift)  
[sbermarket_kotlin--canary.202.3337683697.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.202.3337683697.kt)  
[sbermarket_react-native--canary.202.3337683697.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.202.3337683697.ts)  
[sberprime_ios-swift--canary.202.3337683697.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.202.3337683697.swift)  
[sberprime_kotlin--canary.202.3337683697.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_kotlin--canary.202.3337683697.kt)  
[sberprime_react-native--canary.202.3337683697.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_react-native--canary.202.3337683697.ts)  
[colors--canary.202.3337683697.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.202.3337683697.xml)  
[PlasmaTokensColor--canary.202.3337683697.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.202.3337683697.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.106.3-canary.202.3337683697.0
  # or 
  yarn add @salutejs/plasma-temple@1.106.3-canary.202.3337683697.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-202/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-202/
  ui storybook: http://plasma.sberdevices.ru/pr-202/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-202/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-202/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-202/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-202/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-202/
  ui storybook: http://plasma.sberdevices.ru/pr-202/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-202/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-202/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-202/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]
А что тут происходит то, что фиксится?

**Comment by LamaEats** [comment]
> А что тут происходит то, что фиксится?

пересчет кол-ва слайдов если они динамически меняются
и фикс для переноса текста в заголовке слайда

**Pull request merged**
