### PR TITLE
fix(plasma-hope): change withAssistiveDropdown return type to ForwardRef

### PR DESCRIPTION
**Pull request by Yakutoc**
Необходимо было изменить/добавить метод `withAssistiveDropdown` что бы он могу вернуть `ForwardRef` и можно было бы прокинуть ref.

Было: 

```
Function components cannot have refs. Did you mean to use React.forwardRef()
```      

Стало: 

Screenshot 2023-03-07 at 16 54 40

:baby_chick: Download canary assets:

[colors--canary.393.4352994230.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.393.4352994230.xml)  
[color_metro_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.393.4352994230.swift)  
[color_metro_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.393.4352994230.kt)  
[color_metro_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.393.4352994230.ts)  
[color_sberHealth_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.393.4352994230.swift)  
[color_sberHealth_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.393.4352994230.kt)  
[color_sberHealth_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.393.4352994230.ts)  
[color_sbermarket_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.393.4352994230.swift)  
[color_sbermarket_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.393.4352994230.kt)  
[color_sbermarket_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.393.4352994230.ts)  
[color_sberprime_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.393.4352994230.swift)  
[color_sberprime_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.393.4352994230.kt)  
[color_sberprime_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.393.4352994230.ts)  
[color_selgros_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.393.4352994230.swift)  
[color_selgros_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.393.4352994230.kt)  
[color_selgros_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.393.4352994230.ts)  
[color_smbusiness_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.393.4352994230.swift)  
[color_smbusiness_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.393.4352994230.kt)  
[color_smbusiness_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.393.4352994230.ts)  
[PlasmaTokensColor--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.393.4352994230.swift)  
[shadow_sbermarket_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.393.4352994230.ts)  
[typo_mage_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.393.4352994230.swift)  
[typo_mage_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.393.4352994230.kt)  
[typo_mage_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.393.4352994230.ts)  
[typo_plasma_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.393.4352994230.swift)  
[typo_plasma_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.393.4352994230.kt)  
[typo_plasma_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.393.4352994230.ts)  
[typo_ruler_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.393.4352994230.swift)  
[typo_ruler_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.393.4352994230.kt)  
[typo_ruler_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.393.4352994230.ts)  
[typo_sage_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.393.4352994230.swift)  
[typo_sage_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.393.4352994230.kt)  
[typo_sage_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.393.4352994230.ts)  
[typo_sbermarket_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.393.4352994230.swift)  
[typo_sbermarket_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.393.4352994230.kt)  
[typo_sbermarket_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.393.4352994230.ts)  
[typo_soulmate_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.393.4352994230.swift)  
[typo_soulmate_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.393.4352994230.kt)  
[typo_soulmate_react-native--canary.393.4352994230.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.393.4352994230.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.156.0-canary.393.4352994230.0
  npm install @salutejs/plasma-hope@0.15.0-canary.393.4352994230.0
  npm install @salutejs/plasma-web@1.181.0-canary.393.4352994230.0
  # or 
  yarn add @salutejs/plasma-b2c@1.156.0-canary.393.4352994230.0
  yarn add @salutejs/plasma-hope@0.15.0-canary.393.4352994230.0
  yarn add @salutejs/plasma-web@1.181.0-canary.393.4352994230.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-393/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-393/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-393/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-393/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-393/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-393/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-393/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
