### PR TITLE
feat(plasma-tokens): Add gradient generators

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.170.3150944806.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.170.3150944806.swift)  
[sbermarket_kotlin--canary.170.3150944806.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.170.3150944806.kt)  
[sbermarket_react-native--canary.170.3150944806.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.170.3150944806.ts)  
[colors--canary.170.3150944806.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.170.3150944806.xml)  
[PlasmaTokensColor--canary.170.3150944806.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.170.3150944806.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.97.0-canary.170.3150944806.0
  npm install @salutejs/plasma-core@1.74.0-canary.170.3150944806.0
  npm install @salutejs/plasma-icons@1.100.0-canary.170.3150944806.0
  npm install @salutejs/plasma-temple@1.97.0-canary.170.3150944806.0
  npm install @salutejs/plasma-tokens@1.26.0-canary.170.3150944806.0
  npm install @salutejs/plasma-typo@0.21.0-canary.170.3150944806.0
  npm install @salutejs/plasma-ui@1.131.0-canary.170.3150944806.0
  npm install @salutejs/plasma-web@1.130.0-canary.170.3150944806.0
  npm install @salutejs/plasma-cy-utils@0.27.0-canary.170.3150944806.0
  npm install @salutejs/plasma-sb-utils@0.73.0-canary.170.3150944806.0
  npm install @salutejs/plasma-tokens-android@2.33.0-canary.170.3150944806.0
  npm install @salutejs/plasma-tokens-ios-swift@2.33.0-canary.170.3150944806.0
  # or 
  yarn add @salutejs/plasma-b2c@1.97.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-core@1.74.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-icons@1.100.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-temple@1.97.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-tokens@1.26.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-typo@0.21.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-ui@1.131.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-web@1.130.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-cy-utils@0.27.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-sb-utils@0.73.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-tokens-android@2.33.0-canary.170.3150944806.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.33.0-canary.170.3150944806.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-170/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-170/
  ui storybook: http://plasma.sberdevices.ru/pr-170/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-170/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-170/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-170/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-170/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-170/
  ui storybook: http://plasma.sberdevices.ru/pr-170/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-170/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-170/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-170/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-170/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-170/

**Review by Yakutoc — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-170/
  ui storybook: http://plasma.sberdevices.ru/pr-170/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-170/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-170/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-170/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-170/
  ui storybook: http://plasma.sberdevices.ru/pr-170/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-170/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-170/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-170/temple-storybook/

**Pull request merged**
