### PR TITLE
fix(plasma-ui): scroll carousel on touch devices

### PR DESCRIPTION
**Pull request by arsenykruglikov**
:baby_chick: Download canary assets:

[colors--canary.169.3100157986.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.169.3100157986.xml)  
[PlasmaTokensColor--canary.169.3100157986.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.169.3100157986.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.95.2-canary.169.3100157986.0
  npm install @salutejs/plasma-core@1.72.2-canary.169.3100157986.0
  npm install @salutejs/plasma-icons@1.98.2-canary.169.3100157986.0
  npm install @salutejs/plasma-temple@1.95.3-canary.169.3100157986.0
  npm install @salutejs/plasma-typo@0.19.2-canary.169.3100157986.0
  npm install @salutejs/plasma-ui@1.129.2-canary.169.3100157986.0
  npm install @salutejs/plasma-web@1.128.2-canary.169.3100157986.0
  npm install @salutejs/plasma-cy-utils@0.25.2-canary.169.3100157986.0
  npm install @salutejs/plasma-sb-utils@0.71.2-canary.169.3100157986.0
  # or 
  yarn add @salutejs/plasma-b2c@1.95.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-core@1.72.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-icons@1.98.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-temple@1.95.3-canary.169.3100157986.0
  yarn add @salutejs/plasma-typo@0.19.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-ui@1.129.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-web@1.128.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-cy-utils@0.25.2-canary.169.3100157986.0
  yarn add @salutejs/plasma-sb-utils@0.71.2-canary.169.3100157986.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-169/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-169/
  ui storybook: http://plasma.sberdevices.ru/pr-169/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-169/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-169/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-169/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-169/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-169/
  ui storybook: http://plasma.sberdevices.ru/pr-169/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-169/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-169/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-169/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-169/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-169/
  ui storybook: http://plasma.sberdevices.ru/pr-169/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-169/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-169/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-169/temple-storybook/

**Review by KateKate — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Review by RPG59 — APPROVED** [review]

**Pull request merged**
