### PR TITLE
feat(plasma-typo): typo by archetype

### PR DESCRIPTION
**Pull request by kvpolyanskiy**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.94.0-canary.129.3044304403.0
  npm install @salutejs/plasma-core@1.71.0-canary.129.3044304403.0
  npm install @salutejs/plasma-temple@1.94.0-canary.129.3044304403.0
  npm install @salutejs/plasma-typo@0.18.0-canary.129.3044304403.0
  npm install @salutejs/plasma-ui@1.128.0-canary.129.3044304403.0
  npm install @salutejs/plasma-web@1.127.0-canary.129.3044304403.0
  npm install @salutejs/plasma-cy-utils@0.24.0-canary.129.3044304403.0
  # or 
  yarn add @salutejs/plasma-b2c@1.94.0-canary.129.3044304403.0
  yarn add @salutejs/plasma-core@1.71.0-canary.129.3044304403.0
  yarn add @salutejs/plasma-temple@1.94.0-canary.129.3044304403.0
  yarn add @salutejs/plasma-typo@0.18.0-canary.129.3044304403.0
  yarn add @salutejs/plasma-ui@1.128.0-canary.129.3044304403.0
  yarn add @salutejs/plasma-web@1.127.0-canary.129.3044304403.0
  yarn add @salutejs/plasma-cy-utils@0.24.0-canary.129.3044304403.0
  ```
</details>

:baby_chick: Download canary assets:

[colors--canary.129.3044304403.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.129.3044304403.xml)  
[PlasmaTokensColor--canary.129.3044304403.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.129.3044304403.swift)

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-129/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-129/
  ui storybook: http://plasma.sberdevices.ru/pr-129/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-129/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-129/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-129/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-129/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-129/
  ui storybook: http://plasma.sberdevices.ru/pr-129/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-129/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-129/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-129/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-129/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-129/
  ui storybook: http://plasma.sberdevices.ru/pr-129/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-129/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-129/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-129/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-129/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-129/
  ui storybook: http://plasma.sberdevices.ru/pr-129/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-129/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-129/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-129/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-129/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-129/
  ui storybook: http://plasma.sberdevices.ru/pr-129/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-129/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-129/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-129/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
