### PR TITLE
docs: update import deprecated darkSber

### LINKED ISSUE #771: Docs [Настройка]: deprecated import in GlobalStyle.tsx example
[Настройка](https://plasma.sberdevices.ru/versions/ui-1.181.1/#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0)   has [import darkSber](https://github.com/salute-developers/plasma/blob/547934c899707b6e3d750fa4f1fff65a076762a1/website/plasma-ui-docs/docs/intro.mdx#L43 
) but it has been marked as deprecated at here: https://github.com/salute-developers/plasma/blob/de05b9ae35c1ac03ee7c16ed4d1e5728b240aaaa/packages/plasma-tokens/src/themes/salutejs_sber__dark.ts#L81

### PR DESCRIPTION
**Pull request by azeek21**
fixes #771

### CODE REVIEW

**Comment by Yeti-or** [comment]
@azeek21 could you squash commits to one and use just `docs: update import deprecated darkSber` as commit message instead of chore [docs]

**Comment by Yeti-or** [comment]
We have some issues with pipelines, but no worries we merge it anyway

**Review by neretin-trike — APPROVED** [review]

**Comment by Yeti-or** [comment]
Thank's for pr

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.232.0-dev.0, @salutejs/plasma-hope@1.232.0-dev.0, @salutejs/plasma-new-hope@0.2.0-dev.0, @salutejs/plasma-temple-docs@0.169.0-dev.0, @salutejs/plasma-ui-docs@0.218.0-dev.0, @salutejs/plasma-web-docs@0.186.0-dev.0, @salutejs/plasma-web@1.232.0-dev.0, @salutejs/plasma-website@0.194.0-dev.0 🚀

**Pull request merged**
