### PR TITLE
fix(plasma-temple): useSpatNavBetweenTargets - fix ssr render

### PR DESCRIPTION
**Pull request by kvpolyanskiy**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.72.2-canary.59.2460804781.0
  # or 
  yarn add @salutejs/plasma-temple@1.72.2-canary.59.2460804781.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-59/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-59/
  ui storybook: http://plasma.sberdevices.ru/pr-59/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-59/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-59/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-59/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-59/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-59/
  ui storybook: http://plasma.sberdevices.ru/pr-59/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-59/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-59/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-59/temple-storybook/

**Review by LamaEats — APPROVED** [review]

**Pull request merged**
