### PR TITLE
plasma-infra: Setup dev stage [Part 2]

### PR DESCRIPTION
**Pull request by Yakutoc**
### What/why changed

Расширили список пакетов для deploy на dev stage

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1037/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1037/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1037/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1037/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1037/

**Review by neretin-trike — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.282.1-dev.0, @salutejs/plasma-hope@1.261.1-dev.0, @salutejs/plasma-temple-docs@0.220.1-dev.0, @salutejs/plasma-ui-docs@0.269.1-dev.0, @salutejs/plasma-web-docs@0.236.1-dev.0, @salutejs/plasma-web@1.282.1-dev.0, @salutejs/plasma-website@0.244.1-dev.0 🚀

**Pull request merged**
