### PR TITLE
ci: fix size of ts report

### PR DESCRIPTION
**Pull request by Yeti-or**
:baby_chick: Download canary assets:

[colors--canary.283.3948618005.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.283.3948618005.xml)  
[color_metro_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.283.3948618005.swift)  
[color_metro_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.283.3948618005.kt)  
[color_metro_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.283.3948618005.ts)  
[color_sbermarket_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.283.3948618005.swift)  
[color_sbermarket_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.283.3948618005.kt)  
[color_sbermarket_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.283.3948618005.ts)  
[color_sberprime_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.283.3948618005.swift)  
[color_sberprime_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.283.3948618005.kt)  
[color_sberprime_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.283.3948618005.ts)  
[color_selgros_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.283.3948618005.swift)  
[color_selgros_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.283.3948618005.kt)  
[color_selgros_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.283.3948618005.ts)  
[color_smbusiness_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.283.3948618005.swift)  
[color_smbusiness_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.283.3948618005.kt)  
[color_smbusiness_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.283.3948618005.ts)  
[PlasmaTokensColor--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.283.3948618005.swift)  
[typo_mage_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.283.3948618005.swift)  
[typo_mage_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.283.3948618005.kt)  
[typo_mage_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.283.3948618005.ts)  
[typo_plasma_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.283.3948618005.swift)  
[typo_plasma_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.283.3948618005.kt)  
[typo_plasma_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.283.3948618005.ts)  
[typo_ruler_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.283.3948618005.swift)  
[typo_ruler_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.283.3948618005.kt)  
[typo_ruler_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.283.3948618005.ts)  
[typo_sage_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.283.3948618005.swift)  
[typo_sage_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.283.3948618005.kt)  
[typo_sage_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.283.3948618005.ts)  
[typo_sbermarket_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.283.3948618005.swift)  
[typo_sbermarket_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.283.3948618005.kt)  
[typo_sbermarket_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.283.3948618005.ts)  
[typo_soulmate_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.283.3948618005.swift)  
[typo_soulmate_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.283.3948618005.kt)  
[typo_soulmate_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.283.3948618005.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.125.1-canary.283.3948618005.0
  npm install @salutejs/plasma-core@1.88.1-canary.283.3948618005.0
  npm install @salutejs/plasma-icons@1.116.1-canary.283.3948618005.0
  npm install @salutejs/plasma-temple@1.122.1-canary.283.3948618005.0
  npm install @salutejs/plasma-ui@1.155.1-canary.283.3948618005.0
  npm install @salutejs/plasma-web@1.152.1-canary.283.3948618005.0
  npm install @salutejs/plasma-cy-utils@0.38.1-canary.283.3948618005.0
  npm install @salutejs/plasma-sb-utils@0.86.1-canary.283.3948618005.0
  # or 
  yarn add @salutejs/plasma-b2c@1.125.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-core@1.88.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-icons@1.116.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-temple@1.122.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-ui@1.155.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-web@1.152.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-cy-utils@0.38.1-canary.283.3948618005.0
  yarn add @salutejs/plasma-sb-utils@0.86.1-canary.283.3948618005.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-283/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-283/

**Comment by Yeti-or** [comment]
Было: 
Screenshot 2023-01-18 at 15 19 54

Стало:
Screenshot 2023-01-18 at 15 20 13

**Review by Yakutoc — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-283/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-283/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-283/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-283/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-283/temple-storybook/

**Pull request merged**
