### PR TITLE
 feat(plasma-tokens): Add `sberprime` theme

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.182.3279227055.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.182.3279227055.swift)  
[sbermarket_kotlin--canary.182.3279227055.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.182.3279227055.kt)  
[sbermarket_react-native--canary.182.3279227055.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.182.3279227055.ts)  
[sberprime_ios-swift--canary.182.3279227055.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.182.3279227055.swift)  
[sberprime_kotlin--canary.182.3279227055.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_kotlin--canary.182.3279227055.kt)  
[sberprime_react-native--canary.182.3279227055.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_react-native--canary.182.3279227055.ts)  
[colors--canary.182.3279227055.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.182.3279227055.xml)  
[PlasmaTokensColor--canary.182.3279227055.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.182.3279227055.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.103.0-canary.182.3279227055.0
  npm install @salutejs/plasma-core@1.77.0-canary.182.3279227055.0
  npm install @salutejs/plasma-icons@1.103.0-canary.182.3279227055.0
  npm install @salutejs/plasma-temple@1.103.0-canary.182.3279227055.0
  npm install @salutejs/plasma-tokens@1.27.0-canary.182.3279227055.0
  npm install @salutejs/plasma-typo@0.24.0-canary.182.3279227055.0
  npm install @salutejs/plasma-ui@1.137.0-canary.182.3279227055.0
  npm install @salutejs/plasma-web@1.135.0-canary.182.3279227055.0
  npm install @salutejs/plasma-cy-utils@0.30.0-canary.182.3279227055.0
  npm install @salutejs/plasma-sb-utils@0.76.0-canary.182.3279227055.0
  npm install @salutejs/plasma-tokens-android@2.34.0-canary.182.3279227055.0
  npm install @salutejs/plasma-tokens-ios-swift@2.34.0-canary.182.3279227055.0
  # or 
  yarn add @salutejs/plasma-b2c@1.103.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-core@1.77.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-icons@1.103.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-temple@1.103.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-tokens@1.27.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-typo@0.24.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-ui@1.137.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-web@1.135.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-cy-utils@0.30.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-sb-utils@0.76.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-tokens-android@2.34.0-canary.182.3279227055.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.34.0-canary.182.3279227055.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-182/
  ui storybook: http://plasma.sberdevices.ru/pr-182/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-182/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-182/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-182/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-182/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-182/
  ui storybook: http://plasma.sberdevices.ru/pr-182/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-182/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-182/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-182/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-182/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-182/
  ui storybook: http://plasma.sberdevices.ru/pr-182/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-182/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-182/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-182/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
