### PR TITLE
fix(plasma-ui): hidden unnecessary pseudo-placeholder

### PR DESCRIPTION
**Pull request by Yakutoc**
Решение для проблемы #246 

Из-за того что теперь нет наложения цветов placeholder + псевдо placeholder поменялись скриншоты тестов.     

**Примечание:**
 
проблема воспроизводиться в мобильном приложение. 

При чем в андроид студии - нет, только на физическом устройстве, оба раза на телефонах Samsung.      

:baby_chick: Download canary assets:

[colors--canary.271.3746772746.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.271.3746772746.xml)  
[color_metro_ios-swift--canary.271.3746772746.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.271.3746772746.swift)  
[color_metro_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.271.3746772746.kt)  
[color_metro_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.271.3746772746.ts)  
[color_sbermarket_ios-swift--canary.271.3746772746.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.271.3746772746.swift)  
[color_sbermarket_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.271.3746772746.kt)  
[color_sbermarket_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.271.3746772746.ts)  
[color_sberprime_ios-swift--canary.271.3746772746.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.271.3746772746.swift)  
[color_sberprime_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.271.3746772746.kt)  
[color_sberprime_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.271.3746772746.ts)  
[color_selgros_ios-swift--canary.271.3746772746.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.271.3746772746.swift)  
[color_selgros_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.271.3746772746.kt)  
[color_selgros_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.271.3746772746.ts)  
[color_smbusiness_ios-swift--canary.271.3746772746.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.271.3746772746.swift)  
[color_smbusiness_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.271.3746772746.kt)  
[color_smbusiness_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.271.3746772746.ts)  
[PlasmaTokensColor--canary.271.3746772746.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.271.3746772746.swift)  
[typo_mage_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.271.3746772746.kt)  
[typo_mage_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.271.3746772746.ts)  
[typo_plasma_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.271.3746772746.kt)  
[typo_plasma_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.271.3746772746.ts)  
[typo_ruler_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.271.3746772746.kt)  
[typo_ruler_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.271.3746772746.ts)  
[typo_sage_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.271.3746772746.kt)  
[typo_sage_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.271.3746772746.ts)  
[typo_sbermarket_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.271.3746772746.kt)  
[typo_sbermarket_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.271.3746772746.ts)  
[typo_soulmate_kotlin--canary.271.3746772746.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.271.3746772746.kt)  
[typo_soulmate_react-native--canary.271.3746772746.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.271.3746772746.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.118.1-canary.271.3746772746.0
  npm install @salutejs/plasma-ui@1.151.1-canary.271.3746772746.0
  # or 
  yarn add @salutejs/plasma-temple@1.118.1-canary.271.3746772746.0
  yarn add @salutejs/plasma-ui@1.151.1-canary.271.3746772746.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-271/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-271/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-271/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-271/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-271/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-271/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-271/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-271/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-271/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-271/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-271/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-271/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-271/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-271/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-271/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-271/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-271/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-271/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
