### PR TITLE
feat(plasma-*): Remove declarationMap from tsconfig.json

### PR DESCRIPTION
**Pull request by neretin-trike**
:baby_chick: Download canary assets:

[colors--canary.326.4171358468.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.326.4171358468.xml)  
[color_metro_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.326.4171358468.swift)  
[color_metro_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.326.4171358468.kt)  
[color_metro_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.326.4171358468.ts)  
[color_sbermarket_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.326.4171358468.swift)  
[color_sbermarket_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.326.4171358468.kt)  
[color_sbermarket_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.326.4171358468.ts)  
[color_sberprime_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.326.4171358468.swift)  
[color_sberprime_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.326.4171358468.kt)  
[color_sberprime_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.326.4171358468.ts)  
[color_selgros_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.326.4171358468.swift)  
[color_selgros_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.326.4171358468.kt)  
[color_selgros_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.326.4171358468.ts)  
[color_smbusiness_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.326.4171358468.swift)  
[color_smbusiness_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.326.4171358468.kt)  
[color_smbusiness_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.326.4171358468.ts)  
[PlasmaTokensColor--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.326.4171358468.swift)  
[shadow_sbermarket_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.326.4171358468.ts)  
[typo_mage_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.326.4171358468.swift)  
[typo_mage_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.326.4171358468.kt)  
[typo_mage_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.326.4171358468.ts)  
[typo_plasma_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.326.4171358468.swift)  
[typo_plasma_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.326.4171358468.kt)  
[typo_plasma_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.326.4171358468.ts)  
[typo_ruler_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.326.4171358468.swift)  
[typo_ruler_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.326.4171358468.kt)  
[typo_ruler_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.326.4171358468.ts)  
[typo_sage_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.326.4171358468.swift)  
[typo_sage_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.326.4171358468.kt)  
[typo_sage_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.326.4171358468.ts)  
[typo_sbermarket_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.326.4171358468.swift)  
[typo_sbermarket_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.326.4171358468.kt)  
[typo_sbermarket_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.326.4171358468.ts)  
[typo_soulmate_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.326.4171358468.swift)  
[typo_soulmate_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.326.4171358468.kt)  
[typo_soulmate_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.326.4171358468.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.139.0-canary.326.4171358468.0
  npm install @salutejs/cra-template-plasma-basic-template@2.3.0-canary.326.4171358468.0
  npm install @salutejs/plasma-core@1.96.0-canary.326.4171358468.0
  npm install @salutejs/plasma-icons@1.124.0-canary.326.4171358468.0
  npm install @salutejs/plasma-temple@1.133.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens-b2b@1.9.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens-b2c@0.18.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens-web@1.24.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens@1.35.0-canary.326.4171358468.0
  npm install @salutejs/plasma-typo@0.31.0-canary.326.4171358468.0
  npm install @salutejs/plasma-ui@1.166.0-canary.326.4171358468.0
  npm install @salutejs/plasma-web@1.165.0-canary.326.4171358468.0
  npm install @salutejs/plasma-cy-utils@0.42.0-canary.326.4171358468.0
  npm install @salutejs/plasma-sb-utils@0.94.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens-android@2.42.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens-ios-swift@2.42.0-canary.326.4171358468.0
  npm install @salutejs/plasma-tokens-utils@0.17.0-canary.326.4171358468.0
  # or 
  yarn add @salutejs/plasma-b2c@1.139.0-canary.326.4171358468.0
  yarn add @salutejs/cra-template-plasma-basic-template@2.3.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-core@1.96.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-icons@1.124.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-temple@1.133.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens-b2b@1.9.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens-b2c@0.18.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens-web@1.24.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens@1.35.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-typo@0.31.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-ui@1.166.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-web@1.165.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-cy-utils@0.42.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-sb-utils@0.94.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens-android@2.42.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens-ios-swift@2.42.0-canary.326.4171358468.0
  yarn add @salutejs/plasma-tokens-utils@0.17.0-canary.326.4171358468.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-326/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-326/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-326/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-326/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-326/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-326/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-326/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-326/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **💀 Missing report, something went wrong**

Check out current report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-326/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-326/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-326/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-326/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-326/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-326/temple-storybook/

**Comment by Yakutoc** [comment]
@neretin-trike Привет, а какая мотивация для удаления этой опции конфигурации компилятора?

**Comment by neretin-trike** [comment]
> @neretin-trike Привет, а какая мотивация для удаления этой опции конфигурации компилятора?

по сути оно ни для чего не нужна и только увеличивает вес тарника

**Review by Yakutoc — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-326/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-326/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-326/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-326/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-326/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-326/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-326/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

**Review by LamaEats — APPROVED** [review]

**Pull request merged**
