### PR TITLE
feat(plasma-b2c): Add Calendar

### PR DESCRIPTION
**Pull request by Yeti-or**
:baby_chick: Download canary assets:

[sbermarket_ios-swift--canary.191.3284157078.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.191.3284157078.swift)  
[sbermarket_kotlin--canary.191.3284157078.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.191.3284157078.kt)  
[sbermarket_react-native--canary.191.3284157078.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.191.3284157078.ts)  
[sberprime_ios-swift--canary.191.3284157078.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.191.3284157078.swift)  
[sberprime_kotlin--canary.191.3284157078.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_kotlin--canary.191.3284157078.kt)  
[sberprime_react-native--canary.191.3284157078.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_react-native--canary.191.3284157078.ts)  
[colors--canary.191.3284157078.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.191.3284157078.xml)  
[PlasmaTokensColor--canary.191.3284157078.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.191.3284157078.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.104.0-canary.191.3284157078.0
  npm install @salutejs/plasma-web@1.136.0-canary.191.3284157078.0
  # or 
  yarn add @salutejs/plasma-b2c@1.104.0-canary.191.3284157078.0
  yarn add @salutejs/plasma-web@1.136.0-canary.191.3284157078.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-191/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-191/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-191/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-191/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-191/
  ui storybook: http://plasma.sberdevices.ru/pr-191/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-191/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-191/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-191/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
