### PR TITLE
plasma-infra: run workflow by condition [Performance Testing] [Part 2]

### PR DESCRIPTION
**Pull request by Yakutoc**
Добавляем похожую логику как тут #558 только для  "Performance Testing". 

Логика будет немного другой, этот workflow будет запускаться **только когда есть изменения в компонентах** `plasma-web/b2c/ui/temple`.

Screenshot 2023-06-20 at 14 23 20

--------

То есть, если изменения будут в пакете `plasma-icons`, то данный workflow **не запуститься** в отличие от workflow для cypress , где 

> Если есть изменения в таких пакетах как typo, tokens, icons, etc то нужно запускать тесты для всех scope! 

Screenshot 2023-06-20 at 14 25 41

#### Когда нет вообще никаких изменений связанных с компонентами и их зависимостями
    
Screenshot 2023-06-20 at 14 34 17

#### Изменения в `@salutejs/plasma-ui-docs`
 
Screenshot 2023-06-20 at 14 47 14
      

:baby_chick: Download canary assets:

[color_asdk_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.566.5354264334.swift)  
[color_asdk_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.566.5354264334.kt)  
[color_asdk_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.566.5354264334.ts)  
[color_sberHealth_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.566.5354264334.swift)  
[color_sberHealth_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.566.5354264334.kt)  
[color_sberHealth_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.566.5354264334.ts)  
[color_sbermarket_business_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.566.5354264334.swift)  
[color_sbermarket_business_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.566.5354264334.kt)  
[color_sbermarket_business_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.566.5354264334.ts)  
[color_sbermarket_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.566.5354264334.swift)  
[color_sbermarket_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.566.5354264334.kt)  
[color_sbermarket_metro_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.566.5354264334.swift)  
[color_sbermarket_metro_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.566.5354264334.kt)  
[color_sbermarket_metro_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.566.5354264334.ts)  
[color_sbermarket_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.566.5354264334.ts)  
[color_sbermarket_selgros_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.566.5354264334.swift)  
[color_sbermarket_selgros_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.566.5354264334.kt)  
[color_sbermarket_selgros_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.566.5354264334.ts)  
[color_sbermarket_wlbusiness_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.566.5354264334.swift)  
[color_sbermarket_wlbusiness_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.566.5354264334.kt)  
[color_sbermarket_wlbusiness_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.566.5354264334.ts)  
[color_sberonline_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_ios-swift--canary.566.5354264334.swift)  
[color_sberonline_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_kotlin--canary.566.5354264334.kt)  
[color_sberonline_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_react-native--canary.566.5354264334.ts)  
[color_sberprime_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.566.5354264334.swift)  
[color_sberprime_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.566.5354264334.kt)  
[color_sberprime_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.566.5354264334.ts)  
[shadow_sbermarket_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.566.5354264334.ts)  
[typo_mage_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.566.5354264334.swift)  
[typo_mage_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.566.5354264334.kt)  
[typo_mage_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.566.5354264334.ts)  
[typo_plasma_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.566.5354264334.swift)  
[typo_plasma_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.566.5354264334.kt)  
[typo_plasma_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.566.5354264334.ts)  
[typo_ruler_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.566.5354264334.swift)  
[typo_ruler_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.566.5354264334.kt)  
[typo_ruler_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.566.5354264334.ts)  
[typo_sage_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.566.5354264334.swift)  
[typo_sage_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.566.5354264334.kt)  
[typo_sage_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.566.5354264334.ts)  
[typo_sbermarket_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.566.5354264334.swift)  
[typo_sbermarket_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.566.5354264334.kt)  
[typo_sbermarket_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.566.5354264334.ts)  
[typo_soulmate_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.566.5354264334.swift)  
[typo_soulmate_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.566.5354264334.kt)  
[typo_soulmate_react-native--canary.566.5354264334.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.566.5354264334.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.217.1-canary.566.5354264334.0
  npm install @salutejs/plasma-hope@1.217.1-canary.566.5354264334.0
  npm install @salutejs/plasma-web@1.217.1-canary.566.5354264334.0
  # or 
  yarn add @salutejs/plasma-b2c@1.217.1-canary.566.5354264334.0
  yarn add @salutejs/plasma-hope@1.217.1-canary.566.5354264334.0
  yarn add @salutejs/plasma-web@1.217.1-canary.566.5354264334.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-566/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-566/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-566/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-566/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-566/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-566/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-566/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-566/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-566/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-566/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-566/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-566/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-566/temple-storybook/

**Review by kayman233 — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
