### PR TITLE
feat(plasma-tokens-utils): Add exclude `enabled=false` tokens from generated themes

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>:baby_chick: Download canary assets:</summary>
  <blockquote>
    <details>
      <summary>color</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.617.5553797887.swift'>color_asdk_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.617.5553797887.kt'>color_asdk_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.617.5553797887.ts'>color_asdk_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_xml--canary.617.5553797887.xml'>color_asdk_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_ios-swift--canary.617.5553797887.swift'>color_plasma_b2c_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_kotlin--canary.617.5553797887.kt'>color_plasma_b2c_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_react-native--canary.617.5553797887.ts'>color_plasma_b2c_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_xml--canary.617.5553797887.xml'>color_plasma_b2c_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.617.5553797887.swift'>color_sberHealth_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.617.5553797887.kt'>color_sberHealth_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.617.5553797887.ts'>color_sberHealth_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_xml--canary.617.5553797887.xml'>color_sberHealth_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.617.5553797887.swift'>color_sbermarket_business_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_kotlin--canary.617.5553797887.kt'>color_sbermarket_business_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_react-native--canary.617.5553797887.ts'>color_sbermarket_business_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_xml--canary.617.5553797887.xml'>color_sbermarket_business_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.617.5553797887.swift'>color_sbermarket_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.617.5553797887.kt'>color_sbermarket_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_ios-swift--canary.617.5553797887.swift'>color_sbermarket_metro_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_kotlin--canary.617.5553797887.kt'>color_sbermarket_metro_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_react-native--canary.617.5553797887.ts'>color_sbermarket_metro_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_metro_xml--canary.617.5553797887.xml'>color_sbermarket_metro_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.617.5553797887.ts'>color_sbermarket_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_ios-swift--canary.617.5553797887.swift'>color_sbermarket_selgros_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_kotlin--canary.617.5553797887.kt'>color_sbermarket_selgros_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_react-native--canary.617.5553797887.ts'>color_sbermarket_selgros_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_selgros_xml--canary.617.5553797887.xml'>color_sbermarket_selgros_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_ios-swift--canary.617.5553797887.swift'>color_sbermarket_wlbusiness_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_kotlin--canary.617.5553797887.kt'>color_sbermarket_wlbusiness_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_react-native--canary.617.5553797887.ts'>color_sbermarket_wlbusiness_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_wlbusiness_xml--canary.617.5553797887.xml'>color_sbermarket_wlbusiness_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_xml--canary.617.5553797887.xml'>color_sbermarket_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_ios-swift--canary.617.5553797887.swift'>color_sberonline_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_kotlin--canary.617.5553797887.kt'>color_sberonline_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_react-native--canary.617.5553797887.ts'>color_sberonline_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberonline_xml--canary.617.5553797887.xml'>color_sberonline_xml--canary.617.5553797887.xml</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.617.5553797887.swift'>color_sberprime_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.617.5553797887.kt'>color_sberprime_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.617.5553797887.ts'>color_sberprime_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_xml--canary.617.5553797887.xml'>color_sberprime_xml--canary.617.5553797887.xml</a><br>
      </blockquote>
    </details>
    <details>
      <summary>shadow</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/shadow_sbermarket_react-native--canary.617.5553797887.ts'>shadow_sbermarket_react-native--canary.617.5553797887.ts</a><br>
      </blockquote>
    </details>
    <details>
      <summary>typo</summary>
      <blockquote>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.617.5553797887.swift'>typo_mage_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.617.5553797887.kt'>typo_mage_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.617.5553797887.ts'>typo_mage_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.617.5553797887.swift'>typo_plasma_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.617.5553797887.kt'>typo_plasma_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.617.5553797887.ts'>typo_plasma_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.617.5553797887.swift'>typo_ruler_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.617.5553797887.kt'>typo_ruler_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.617.5553797887.ts'>typo_ruler_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.617.5553797887.swift'>typo_sage_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.617.5553797887.kt'>typo_sage_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.617.5553797887.ts'>typo_sage_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.617.5553797887.swift'>typo_sbermarket_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.617.5553797887.kt'>typo_sbermarket_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.617.5553797887.ts'>typo_sbermarket_react-native--canary.617.5553797887.ts</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.617.5553797887.swift'>typo_soulmate_ios-swift--canary.617.5553797887.swift</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.617.5553797887.kt'>typo_soulmate_kotlin--canary.617.5553797887.kt</a><br>
        <a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.617.5553797887.ts'>typo_soulmate_react-native--canary.617.5553797887.ts</a><br>
      </blockquote>
    </details>
  </blockquote>
</details>

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.220.0-canary.617.5553797887.0
  npm install @salutejs/plasma-core@1.125.0-canary.617.5553797887.0
  npm install @salutejs/plasma-hope@1.220.0-canary.617.5553797887.0
  npm install @salutejs/plasma-icons@1.154.0-canary.617.5553797887.0
  npm install @salutejs/plasma-temple@1.169.0-canary.617.5553797887.0
  npm install @salutejs/plasma-tokens-b2b@1.24.0-canary.617.5553797887.0
  npm install @salutejs/plasma-tokens-b2c@0.33.0-canary.617.5553797887.0
  npm install @salutejs/plasma-tokens-web@1.39.0-canary.617.5553797887.0
  npm install @salutejs/plasma-tokens@1.58.0-canary.617.5553797887.0
  npm install @salutejs/plasma-ui@1.201.0-canary.617.5553797887.0
  npm install @salutejs/plasma-web@1.220.0-canary.617.5553797887.0
  npm install @salutejs/plasma-cy-utils@0.65.0-canary.617.5553797887.0
  npm install @salutejs/plasma-sb-utils@0.123.0-canary.617.5553797887.0
  npm install @salutejs/plasma-tokens-utils@0.29.0-canary.617.5553797887.0
  # or 
  yarn add @salutejs/plasma-b2c@1.220.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-core@1.125.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-hope@1.220.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-icons@1.154.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-temple@1.169.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-tokens-b2b@1.24.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-tokens-b2c@0.33.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-tokens-web@1.39.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-tokens@1.58.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-ui@1.201.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-web@1.220.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-cy-utils@0.65.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-sb-utils@0.123.0-canary.617.5553797887.0
  yarn add @salutejs/plasma-tokens-utils@0.29.0-canary.617.5553797887.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-617/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-617/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-617/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-617/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-617/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-617/temple-storybook/

**Review by Yakutoc — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-617/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-617/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-617/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-617/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-617/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-617/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-617/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-617/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-617/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-617/web-storybook/
ui storybook: http://plasma.sberdevices.ru/pr/pr-617/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-617/temple-storybook/

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.220.0, @salutejs/plasma-core@1.125.0, @salutejs/plasma-cy-utils@0.65.0, @salutejs/plasma-hope@1.220.0, @salutejs/plasma-icons@1.154.0, @salutejs/plasma-sb-utils@0.123.0, @salutejs/plasma-temple-docs@0.160.0, @salutejs/plasma-temple@1.169.0, @salutejs/plasma-tokens-b2b@1.24.0, @salutejs/plasma-tokens-b2c@0.33.0, @salutejs/plasma-tokens-native@1.9.0, @salutejs/plasma-tokens-utils@0.29.0, @salutejs/plasma-tokens-web@1.39.0, @salutejs/plasma-tokens@1.58.0, @salutejs/plasma-typo@0.36.0, @salutejs/plasma-ui-docs@0.209.0, @salutejs/plasma-ui@1.201.0, @salutejs/plasma-web-docs@0.178.0, @salutejs/plasma-web@1.220.0, @salutejs/plasma-website@0.186.0 🚀

**Pull request merged**
