### PR TITLE
fix(plasma-temple): focusin(-out) => focus / blur

### PR DESCRIPTION
**Pull request by LamaEats**
:baby_chick: Download canary assets:

[colors--canary.163.3048451902.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.163.3048451902.xml)  
[PlasmaTokensColor--canary.163.3048451902.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.163.3048451902.swift)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.93.1-canary.163.3048451902.0
  # or 
  yarn add @salutejs/plasma-temple@1.93.1-canary.163.3048451902.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-163/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-163/
  ui storybook: http://plasma.sberdevices.ru/pr-163/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-163/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-163/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-163/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-163/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-163/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-163/
  ui storybook: http://plasma.sberdevices.ru/pr-163/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-163/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-163/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-163/temple-storybook/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-163/
  ui storybook: http://plasma.sberdevices.ru/pr-163/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-163/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-163/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-163/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-163/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-163/
  ui storybook: http://plasma.sberdevices.ru/pr-163/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-163/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-163/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-163/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
