### PR TITLE
Release 04.09.2023

### PR DESCRIPTION
**Pull request by Yakutoc**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.226.0-canary.681.6068486727.0
  npm install @salutejs/plasma-colors@0.11.0-canary.681.6068486727.0
  npm install @salutejs/plasma-core@1.129.0-canary.681.6068486727.0
  npm install @salutejs/plasma-hope@1.226.0-canary.681.6068486727.0
  npm install @salutejs/plasma-icons@1.160.0-canary.681.6068486727.0
  npm install @salutejs/cra-template-plasma-shop-template@2.5.0-canary.681.6068486727.0
  npm install @salutejs/plasma-temple@1.175.0-canary.681.6068486727.0
  npm install @salutejs/plasma-tokens-b2b@1.28.0-canary.681.6068486727.0
  npm install @salutejs/plasma-tokens-b2c@0.37.0-canary.681.6068486727.0
  npm install @salutejs/plasma-tokens-core@0.5.0-canary.681.6068486727.0
  npm install @salutejs/plasma-tokens-web@1.43.0-canary.681.6068486727.0
  npm install @salutejs/plasma-tokens@1.62.0-canary.681.6068486727.0
  npm install @salutejs/plasma-typo@0.38.0-canary.681.6068486727.0
  npm install @salutejs/plasma-ui@1.207.0-canary.681.6068486727.0
  npm install @salutejs/plasma-web@1.226.0-canary.681.6068486727.0
  npm install @salutejs/plasma-cy-utils@0.69.0-canary.681.6068486727.0
  npm install @salutejs/plasma-sb-utils@0.127.0-canary.681.6068486727.0
  npm install @salutejs/plasma-tokens-utils@0.32.0-canary.681.6068486727.0
  # or 
  yarn add @salutejs/plasma-b2c@1.226.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-colors@0.11.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-core@1.129.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-hope@1.226.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-icons@1.160.0-canary.681.6068486727.0
  yarn add @salutejs/cra-template-plasma-shop-template@2.5.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-temple@1.175.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-tokens-b2b@1.28.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-tokens-b2c@0.37.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-tokens-core@0.5.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-tokens-web@1.43.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-tokens@1.62.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-typo@0.38.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-ui@1.207.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-web@1.226.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-cy-utils@0.69.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-sb-utils@0.127.0-canary.681.6068486727.0
  yarn add @salutejs/plasma-tokens-utils@0.32.0-canary.681.6068486727.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-681/

**Review by LamaEats — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-681/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-681/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-681/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-681/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-681/

**Pull request merged**
