### PR TITLE
ci: improve ts-coverage report

### PR DESCRIPTION
**Pull request by Yeti-or**
:baby_chick: Download canary assets:

[colors--canary.282.3947329431.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.282.3947329431.xml)  
[color_metro_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.282.3947329431.swift)  
[color_metro_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.282.3947329431.kt)  
[color_metro_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.282.3947329431.ts)  
[color_sbermarket_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.282.3947329431.swift)  
[color_sbermarket_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.282.3947329431.kt)  
[color_sbermarket_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.282.3947329431.ts)  
[color_sberprime_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_ios-swift--canary.282.3947329431.swift)  
[color_sberprime_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_kotlin--canary.282.3947329431.kt)  
[color_sberprime_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberprime_react-native--canary.282.3947329431.ts)  
[color_selgros_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_ios-swift--canary.282.3947329431.swift)  
[color_selgros_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_kotlin--canary.282.3947329431.kt)  
[color_selgros_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_selgros_react-native--canary.282.3947329431.ts)  
[color_smbusiness_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_ios-swift--canary.282.3947329431.swift)  
[color_smbusiness_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_kotlin--canary.282.3947329431.kt)  
[color_smbusiness_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_smbusiness_react-native--canary.282.3947329431.ts)  
[PlasmaTokensColor--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.282.3947329431.swift)  
[typo_mage_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_ios-swift--canary.282.3947329431.swift)  
[typo_mage_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_kotlin--canary.282.3947329431.kt)  
[typo_mage_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_mage_react-native--canary.282.3947329431.ts)  
[typo_plasma_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_ios-swift--canary.282.3947329431.swift)  
[typo_plasma_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_kotlin--canary.282.3947329431.kt)  
[typo_plasma_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_plasma_react-native--canary.282.3947329431.ts)  
[typo_ruler_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_ios-swift--canary.282.3947329431.swift)  
[typo_ruler_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_kotlin--canary.282.3947329431.kt)  
[typo_ruler_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_ruler_react-native--canary.282.3947329431.ts)  
[typo_sage_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_ios-swift--canary.282.3947329431.swift)  
[typo_sage_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_kotlin--canary.282.3947329431.kt)  
[typo_sage_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sage_react-native--canary.282.3947329431.ts)  
[typo_sbermarket_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_ios-swift--canary.282.3947329431.swift)  
[typo_sbermarket_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_kotlin--canary.282.3947329431.kt)  
[typo_sbermarket_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_sbermarket_react-native--canary.282.3947329431.ts)  
[typo_soulmate_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_ios-swift--canary.282.3947329431.swift)  
[typo_soulmate_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_kotlin--canary.282.3947329431.kt)  
[typo_soulmate_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/typo_soulmate_react-native--canary.282.3947329431.ts)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.125.1-canary.282.3947329431.0
  npm install @salutejs/plasma-core@1.88.1-canary.282.3947329431.0
  npm install @salutejs/plasma-icons@1.116.1-canary.282.3947329431.0
  npm install @salutejs/plasma-temple@1.122.1-canary.282.3947329431.0
  npm install @salutejs/plasma-ui@1.155.1-canary.282.3947329431.0
  npm install @salutejs/plasma-web@1.152.1-canary.282.3947329431.0
  npm install @salutejs/plasma-cy-utils@0.38.1-canary.282.3947329431.0
  npm install @salutejs/plasma-sb-utils@0.86.1-canary.282.3947329431.0
  # or 
  yarn add @salutejs/plasma-b2c@1.125.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-core@1.88.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-icons@1.116.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-temple@1.122.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-ui@1.155.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-web@1.152.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-cy-utils@0.38.1-canary.282.3947329431.0
  yarn add @salutejs/plasma-sb-utils@0.86.1-canary.282.3947329431.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-282/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-282/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-282/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-282/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-282/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-282/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-282/temple-storybook/

**Review by Yakutoc — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Pull request merged**
