### PR TITLE
fix(plasma-ui): Toast: clearTimeout after hiding

### PR DESCRIPTION
**Pull request by Yeti-or**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.67.3-canary.26.2367031782.0
  npm install @salutejs/plasma-core@1.59.2-canary.26.2367031782.0
  npm install @salutejs/plasma-icons@1.83.2-canary.26.2367031782.0
  npm install @salutejs/plasma-temple@1.68.3-canary.26.2367031782.0
  npm install @salutejs/plasma-typo@0.6.2-canary.26.2367031782.0
  npm install @salutejs/plasma-ui@1.104.3-canary.26.2367031782.0
  npm install @salutejs/plasma-web@1.102.3-canary.26.2367031782.0
  npm install @salutejs/plasma-cy-utils@0.12.2-canary.26.2367031782.0
  npm install @salutejs/plasma-sb-utils@0.58.3-canary.26.2367031782.0
  # or 
  yarn add @salutejs/plasma-b2c@1.67.3-canary.26.2367031782.0
  yarn add @salutejs/plasma-core@1.59.2-canary.26.2367031782.0
  yarn add @salutejs/plasma-icons@1.83.2-canary.26.2367031782.0
  yarn add @salutejs/plasma-temple@1.68.3-canary.26.2367031782.0
  yarn add @salutejs/plasma-typo@0.6.2-canary.26.2367031782.0
  yarn add @salutejs/plasma-ui@1.104.3-canary.26.2367031782.0
  yarn add @salutejs/plasma-web@1.102.3-canary.26.2367031782.0
  yarn add @salutejs/plasma-cy-utils@0.12.2-canary.26.2367031782.0
  yarn add @salutejs/plasma-sb-utils@0.58.3-canary.26.2367031782.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-26/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-26/
  ui storybook: http://plasma.sberdevices.ru/pr-26/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-26/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-26/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-26/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-26/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-26/
  ui storybook: http://plasma.sberdevices.ru/pr-26/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-26/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-26/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-26/temple-storybook/

**Review by neretin-trike — APPROVED** [review]

**Pull request merged**
