### PR TITLE
plasma-ui: Processing new line for title, subtitle

### PR DESCRIPTION
**Pull request by Yakutoc**
## Release Notes

- Добавлена обработка "новой строки" (`/n`) для `Title`, `Subtitle` 

## What/why Changed

`Title` и `Subtitle` понимают разделитель новой строки.

Например такой заголовок сделает перенос на новую строку
 
```jsx
<Confirm title={'Processing new line by \n and this new line'} />
```     

#### Title
Screenshot 2023-09-04 at 15 23 07

#### Subtitle
Screenshot 2023-09-04 at 15 23 15

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-temple@1.175.0-canary.683.6105752959.0
  npm install @salutejs/plasma-ui@1.207.0-canary.683.6105752959.0
  # or 
  yarn add @salutejs/plasma-temple@1.175.0-canary.683.6105752959.0
  yarn add @salutejs/plasma-ui@1.207.0-canary.683.6105752959.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-683/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by neretin-trike — APPROVED** [review]

**Review by kayman233 — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-683/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-683/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-temple@1.175.0-dev.0, @salutejs/plasma-ui@1.207.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-b2c@1.226.0-dev.0, @salutejs/plasma-core@1.129.0-dev.0, @salutejs/plasma-cy-utils@0.69.0-dev.0, @salutejs/plasma-hope@1.226.0-dev.0, @salutejs/plasma-icons@1.160.0-dev.0, @salutejs/plasma-sb-utils@0.127.0-dev.0, @salutejs/plasma-temple@1.176.0-dev.0, @salutejs/plasma-tokens@1.62.0-dev.0, @salutejs/plasma-ui@1.208.0-dev.0, @salutejs/plasma-web@1.226.0-dev.0 🚀

**Pull request merged**
