### PR TITLE
fix(plasma-core): Fix `Tab` control behavior for Safari

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.85.1-canary.106.2718047501.0
  npm install @salutejs/plasma-core@1.64.3-canary.106.2718047501.0
  npm install @salutejs/plasma-icons@1.90.2-canary.106.2718047501.0
  npm install @salutejs/plasma-temple@1.84.3-canary.106.2718047501.0
  npm install @salutejs/plasma-typo@0.11.3-canary.106.2718047501.0
  npm install @salutejs/plasma-ui@1.118.3-canary.106.2718047501.0
  npm install @salutejs/plasma-web@1.118.3-canary.106.2718047501.0
  npm install @salutejs/plasma-cy-utils@0.17.3-canary.106.2718047501.0
  npm install @salutejs/plasma-sb-utils@0.63.3-canary.106.2718047501.0
  # or 
  yarn add @salutejs/plasma-b2c@1.85.1-canary.106.2718047501.0
  yarn add @salutejs/plasma-core@1.64.3-canary.106.2718047501.0
  yarn add @salutejs/plasma-icons@1.90.2-canary.106.2718047501.0
  yarn add @salutejs/plasma-temple@1.84.3-canary.106.2718047501.0
  yarn add @salutejs/plasma-typo@0.11.3-canary.106.2718047501.0
  yarn add @salutejs/plasma-ui@1.118.3-canary.106.2718047501.0
  yarn add @salutejs/plasma-web@1.118.3-canary.106.2718047501.0
  yarn add @salutejs/plasma-cy-utils@0.17.3-canary.106.2718047501.0
  yarn add @salutejs/plasma-sb-utils@0.63.3-canary.106.2718047501.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-106/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-106/
  ui storybook: http://plasma.sberdevices.ru/pr-106/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-106/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-106/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-106/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-106/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-106/
  ui storybook: http://plasma.sberdevices.ru/pr-106/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-106/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-106/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-106/temple-storybook/

**Review by kvpolyanskiy — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-106/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-106/
  ui storybook: http://plasma.sberdevices.ru/pr-106/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-106/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-106/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-106/temple-storybook/

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-106/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-106/
  ui storybook: http://plasma.sberdevices.ru/pr-106/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-106/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-106/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-106/temple-storybook/

**Pull request merged**
