### PR TITLE
build(plasma-theme-builder): update package-lock

### PR DESCRIPTION
**Pull request by Yeti-or**

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-483/

**Review by neretin-trike — APPROVED** [review]

**Comment by Salute-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-483/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-483/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-483/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-483/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-483/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-483/temple-storybook/

**Comment by Salute-Eva** [comment]
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

**Review by Yakutoc — APPROVED** [review]

**Pull request merged**
