### PR TITLE
plasma-infra: Fix broken build docs

### PR DESCRIPTION
**Pull request by Yakutoc**
### What/why changed

незакрытый тег `img` ломал сборку документации, так как был невалидный JSX

`` - исправил проблему   

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-asdk@0.29.1-canary.987.7582226043.0
  npm install @salutejs/plasma-b2c@1.271.1-canary.987.7582226043.0
  npm install @salutejs/plasma-core@1.144.1-canary.987.7582226043.0
  npm install @salutejs/plasma-hope@1.255.1-canary.987.7582226043.0
  npm install @salutejs/plasma-icons@1.177.1-canary.987.7582226043.0
  npm install @salutejs/plasma-new-hope@0.35.1-canary.987.7582226043.0
  npm install @salutejs/plasma-temple@1.196.1-canary.987.7582226043.0
  npm install @salutejs/plasma-tokens@1.68.1-canary.987.7582226043.0
  npm install @salutejs/plasma-ui@1.228.1-canary.987.7582226043.0
  npm install @salutejs/plasma-web@1.271.1-canary.987.7582226043.0
  npm install @salutejs/plasma-cy-utils@0.76.1-canary.987.7582226043.0
  npm install @salutejs/plasma-sb-utils@0.142.1-canary.987.7582226043.0
  # or 
  yarn add @salutejs/plasma-asdk@0.29.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-b2c@1.271.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-core@1.144.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-hope@1.255.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-icons@1.177.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-new-hope@0.35.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-temple@1.196.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-tokens@1.68.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-ui@1.228.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-web@1.271.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-cy-utils@0.76.1-canary.987.7582226043.0
  yarn add @salutejs/plasma-sb-utils@0.142.1-canary.987.7582226043.0
  ```
</details>

### CODE REVIEW

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-987/

**Comment by Salute-Eva** [comment]
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-987/
ui storybook: http://plasma.sberdevices.ru/pr/pr-987/ui-storybook/
temple storybook: http://plasma.sberdevices.ru/pr/pr-987/temple-storybook/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-987/

**Comment by Salute-Eva** [comment]
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-987/

**Review by Yeti-or — APPROVED** [review]

**Review by TitanKuzmich — APPROVED** [review]

**Comment by Salute-Eva** [comment]
🚀 This PR is included in version: @salutejs/plasma-asdk@0.30.0-dev.0, @salutejs/plasma-b2c@1.272.0-dev.0, @salutejs/plasma-core@1.145.0-dev.0, @salutejs/plasma-cy-utils@0.77.0-dev.0, @salutejs/plasma-hope@1.256.0-dev.0, @salutejs/plasma-icons@1.178.0-dev.0, @salutejs/plasma-new-hope@0.36.0-dev.0, @salutejs/plasma-sb-utils@0.143.0-dev.0, @salutejs/plasma-temple-docs@0.210.0-dev.0, @salutejs/plasma-temple@1.197.0-dev.0, @salutejs/plasma-tokens-native@1.20.0-dev.0, @salutejs/plasma-tokens@1.69.0-dev.0, @salutejs/plasma-ui-docs@0.259.0-dev.0, @salutejs/plasma-ui@1.229.0-dev.0, @salutejs/plasma-web-docs@0.226.0-dev.0, @salutejs/plasma-web@1.272.0-dev.0, @salutejs/plasma-website@0.234.0-dev.0 🚀

**Pull request merged**
